### ISSUE TITLE
dict and intersection defaults 

### ISSUE THREAD

**Issue by panva** [ianstormtaylor/superstruct#104]
Hi @ianstormtaylor,

i have the following use cases for which i've created [tests](https://gist.github.com/panva/9f6239a135ed9436683f749ab0586eb3), that currently fail

1) partial-defaults.js

Shouldn't keys from defaults be returned if not found in data?

2) defaults-partial-dict-one.js and defaults-partial-dict-two.js

Two ways I thought would work to achieve 1) but they're both failing in different ways.

```
  1) superstruct
       dict-scalars
         partial-defaults:

      AssertionError [ERR_ASSERTION]: { b: 3, c: 4 } deepEqual { a: 1, b: 3, c: 4 }
      + expected - actual

       {
      +  "a": 1
         "b": 3
         "c": 4
       }
      
      at Context.it (test/index.js:33:20)

  2) superstruct
       intersection
         defaults-partial-dict-1:

      AssertionError [ERR_ASSERTION]: { a: 3, b: 2 } deepEqual { a: 3, b: 2, c: 5 }
      + expected - actual

       {
         "a": 3
         "b": 2
      +  "c": 5
       }
      
      at Context.it (test/index.js:33:20)

  3) superstruct
       intersection
         defaults-partial-dict-2:
     TypeError: Expected a value of type `dict<string,number> & {a,b,...}` for `b` but received `undefined`.
      at Function.Struct.assert.value [as assert] (lib/index.js:1119:15)
      at Struct (lib/index.js:1103:21)
      at Context.it (test/index.js:32:28)
```

**Comment by ianstormtaylor** [comment]
Hey @panva, you're absolutely right. Those sound like bugs. Would you be willing to submit a PR to fix those? Thanks!

**Comment by panva** [comment]
Hey @ianstormtaylor i'll give it a shot!

**Comment by panva** [comment]
Hi @ianstormtaylor 

it's tests like these https://github.com/ianstormtaylor/superstruct/blob/master/test/fixtures/partial-scalars/valid.js that make me believe what i'm expecting out of defaults and would introduce with a PR would be a breaking change.

essentially in your existing tests you're working with defaults ONLY if the data provided is undefined, they're not used on a per-property level at all.

Your thoughts? I'm keen to think a per property default for all kinds would make sense, but this would be a breaking change you may or may not accept.

Penny for your thoughts

**Comment by panva** [comment]
I have to look at the topics isolated i guess, on thing is defaults - i hope we can agree they should work on a per property level.

Second thing, [partials](https://github.com/ianstormtaylor/superstruct/blob/master/test/fixtures/partial-scalars/property-defaults.js) why not return the extra properties? Is there a structure i can use that lets me do that?
