### ISSUE TITLE
Missing errors in errors array

### ISSUE THREAD

**Issue by davidchase** [ianstormtaylor/superstruct#107]
Hi @ianstormtaylor ,

I saw that its possible to get all of the errors at once based on this issue https://github.com/ianstormtaylor/superstruct/issues/39

However if I have a simple setup like this

```js
const schema = st.object({
  book: st.object({
    bookId: "number",
    pages: "number",
    userId: "number"
  })
})

const data = {
  book: {
    bookId: null,
    pages: null,
    userId: 30201
  }
}
try {
  schema(data)
} catch (err) {
  console.log(err.errors)
}
```
the errors array will only have 1 error for bookId and it missing error object for pages

on the contrary if i just have a single object
```js
const schema = st.object({
  bookId: "number",
  pages: "number",
  userId: "number"
})

const data = {
  bookId: null,
  pages: null,
  userId: 30201
}
try {
  schema(data)
} catch (err) {
  console.log(err.errors)
}
```
the errors array will have 2 errors as expected

This can also be reproduced using a `struct.dict(['string', struct.object({...})])`

Any ideas, is this expected behavior?

**Comment by ianstormtaylor** [comment]
Hey @davidchase, can you copy the error messages you're seeing here? I think I have an idea of what's going on, but not totally sure. Thanks!

**Comment by davidchase** [comment]
hi @ianstormtaylor im not sure what you mean by error messages but if you check out https://stackblitz.com/edit/js-1zmxtm its running the first example, which will show you only one error in the errors array instead of two

**Comment by davidchase** [comment]
any updates with this one? @ianstormtaylor
