### ISSUE TITLE
Add capability to map custom types in array

### ISSUE THREAD

**Issue by siteriaitaliana** [ianstormtaylor/superstruct#110]
If this is supported already please close this not after having provided us an example please :)

E.g.
[
{
"id": "userAdmin",
"permittedActions": [
{
"productId": "userAdmin",
"actionId": "manageUsers",
"permissionId": "readWrite"
}]

**Comment by ianstormtaylor** [comment]
Hey, closing this because there's not enough information and it's really hard to understand what you're asking. Feel free to option a new issue with more detail and with better formatting though!

**Comment by jdolearydl** [comment]
@siteriaitaliana You can validate an array of custom structs like so:
```js
const {struct} = require('superstruct')

const inner = struct({
    test:'number'
    })
// Define a struct to validate with.
const User = struct({
  id: 'number',
  name: 'string',
  email: 'string',
  age: 'number',
  departments: [inner],
  is_admin: 'boolean?',
})

// Define data to be validated.
const data = {
  id: 1,
  name: 'Jane Smith',
  email: 'jane@example.com',
  age: 42,
  departments: [{test:1}, {test:2}],
}

// Validate the data. In this case, the data is valid, so it won't throw.
try {
  User(data)
  console.log('Valid!')
} catch (e) {
  throw e
}
```
