### ISSUE TITLE
Discussion: Compile-Time TypeScript type validation

### ISSUE THREAD

**Issue by charles-toller** [ianstormtaylor/superstruct#113]
The current type definitions located at `@types/superstruct` are good. However, they do not check the type of your struct at compile time, leading to poorer autocomplete as the shape of your struct is not known to TypeScript. A major reason for this is TypeScript's widening of string literals in non-constant contexts. For example, the type of the following struct definition:

```
const def = {
  someProp: 'number'
}
```

is known as:

```
{someProp: string}
```

rather than

```
{someProp: 'number'}
```

This makes it near impossible to write any kind of mapped type that would be valid to your struct. In my research, I have discovered two possible solutions rather than just defaulting to `any`: a shape-only type and more specific struct definitions.

With a shape only type, upon constructing a struct with this definition:

```
const definition = {
  someProp: 'number',
  someObject: {
    anotherProp: 'boolean?'
  }
}
```

you would receive a validation function that has the following type:

```
(objectToTest: any) => {someProp: any, someObject: {anotherProp: any}}
```

This would at least enable autocomplete with your struct's properties, preventing typos at compile time. This does not protect against a property possibly being null (for example, `struct.someObject.anotherProp` can be null in the above example) nor does it actually enforce the types (i.e. number) you've already defined in your struct.

The other option is to use string literal narrowing in your struct definitions, or const enums. For example, if we define a const enum like this:

```
const enum Types {
  String = 'string',
  OptionalString = 'string?'
  Number = 'number',
  OptionalNumber = 'number?'
}
```

it becomes possible to write a mapped type such that a struct definition such as this:

```
const definition = {
  someProp: Types.Number
}
```

returns a struct function with the following type:

```
(objectToTest: any) => {someProp: number}
```

This also works if you force the compiler to not widen the type. The following definition will produce the same type:

```
const definition = {
  someProp: 'number' as 'number'
}
```

The nice thing about using a const enum is that is does not force this library to switch to TypeScript, rather, the enum constants themselves are inlined upon compilation rather than using a static class.

I'm looking here to start a discussion about how to implement such a feature in the typings, and whether any of these solutions I've thought of so far are any good.

**Comment by iFwu** [comment]
TypeScript 3.4 has a new feature to mark object literal as const.

**Comment by charles-toller** [comment]
Even without the 'as const' annotation, objects passed directly into functions in TS 3.4 seem to be narrower typed.

**Comment by charles-toller** [comment]
This is probably blocked by Microsoft/TypeScript#12754, as structs using the union syntax like `string&number` would otherwise require 420 (21 * 20 options) constant definitions in the typical case, and in the custom types case they are impossible to type. We might also want to consider not allowing that syntax to be correctly typed 
(just return `any`), as the number of required types increases quadratically for each custom type (21 (standard) types in system = 420 resultant types, 30 types in system = 870 resultant types).

Optional types are also blocked on this, as both 'customType' and 'customType?' would have to be manually defined by the end consumer otherwise.

**Comment by ianstormtaylor** [comment]
With #139 I've rewritten Superstruct in TypeScript. So hopefully that will make moving forward on this issue slightly easier with less indirection.

I'm less familiar with very complex typings situations though, so I'll need someone else to take lead on this I think.

**Comment by mrmckeb** [comment]
Hi @ianstormtaylor, we've just started using this, and it's great so far. 

As @charles-toller says, we can use TypeScript to validate allowed strings. We'd just need a type like:
```ts
type AllTypes = 'string' | 'string?' | 'number' | 'number?' /* ...and so on */;
```

Users would need to extend this type if they have custom types.

Then we hit types like unions and intersections - where there are infinite possibilities, which is what @charles-toller has also mentioned.

In that case, we could enforce using the helpers instead, and we could use the same list.
```ts
struct.union(['string', 'email']);
```

I'm happy to step in and help with a PR, but I'm not sure what the best direction is... Maybe we do need to wait for https://github.com/microsoft/TypeScript/issues/12754.

**Comment by Aadmaa** [comment]
There's this neat thing Yup has to explicitly generate a type from a Yup schema -- InferType<SchemaType>. I don't know if it's possible to implement something similar for structs, but I wonder if an InferType<StructType> utility might help here? 

https://medium.com/@maurice.de.beijer/yup-validation-and-typescript-and-formik-6c342578a20e

**Comment by thesunny** [comment]
I was looking for / building the same thing and since I like @ianstormtaylor work, decided to take a crack at adding types to superstruct. This won't handle the custom types as of yet (though I think with a bit of work it's possible), but for all the basic types, I think this works. Good for typing API calls with incoming unknown types for example:

```ts
import { struct } from "superstruct"

export type Prettify<T> = T extends Promise<infer V>
  ? Promise<V>
  : T extends infer U
  ? { [K in keyof U]: Prettify<U[K]> }
  : never

type SchemaValue =
  | "string"
  | "string?"
  | "number"
  | "number?"
  | "boolean"
  | "boolean?"
  | ["string" | "number" | "boolean" | SchemaObject]
  | SchemaObject

type SchemaObject = {
  [key: string]: SchemaValue
}

type TypeFromSchemaValue<S extends SchemaValue> = S extends "string"
  ? string
  : S extends "string?"
  ? string | undefined
  : S extends "number"
  ? number
  : S extends "boolean?"
  ? boolean | undefined
  : S extends "boolean"
  ? boolean
  : S extends SchemaObject
  ? TypeFromSchema<S>
  : S extends [infer T]
  ? T extends SchemaValue
    ? T[]
    : never
  : never

type TypeFromSchema<S extends SchemaObject> = {
  [K in keyof S]: TypeFromSchemaValue<S[K]>
}

export function typedStruct<S extends SchemaObject>(schema: S) {
  const validate = struct(schema)
  return (value: unknown): Prettify<TypeFromSchema<S>> => {
    try {
      validate(value)
      return value as Prettify<TypeFromSchema<S>>
    } catch (e) {
      e.message = `${e.message} for schema ${JSON.stringify(
        schema
      )} and value ${JSON.stringify(value)}`
      throw e
    }
  }
}
```

And here's a simple jest unit test that passes:

```ts
import { typedStruct } from "."

describe("guard-schema", () => {
  it("should guard a user (superstruct example)", async () => {
    const User = typedStruct({
      id: "number",
      title: "string",
      is_published: "boolean?",
      tags: ["string"],
      author: {
        id: "number",
      },
    })
    const user = User({
      id: 123,
      title: "John",
      tags: ["dude", "cool"],
      author: { id: 234 },
    })
    expect(user).toEqual({
      id: 123,
      title: "John",
      tags: ["dude", "cool"],
      author: { id: 234 },
    })
  })

  it("should guard a user more complete", async () => {
    const User = typedStruct({
      id: "number",
      title: "string",
      is_published: "boolean?",
      tags: ["string"],
      friend_ids: ["number"],
      booleans: ["boolean"],
      author: {
        id: "number",
      },
      chickens: [{ name: "string", happy: "boolean" }],
    })
    const user = User({
      id: 123,
      title: "John",
      tags: ["dude", "cool"],
      friend_ids: [1, 2, 3],
      booleans: [true, false],
      author: { id: 234 },
      chickens: [
        { name: "plucky", happy: true },
        { name: "cross-the-road", happy: false },
      ],
    })
  })
})
```

And to show that it works, here's the typing information from VSCode:

![image](https://user-images.githubusercontent.com/469587/77263641-0b40ba00-6c56-11ea-832d-c47a946287ec.png)

Maybe I'll create an NPM package for this...

**Comment by jonavila** [comment]
@thesunny Thanks for putting together these types. Any thoughts on how to support `struct.enum(['someValue'])`

**Comment by thesunny** [comment]
@jonavila 

I don't know that much about superstruct and am new to typescript; however, I'd look to turning `['someValue', 'otherValue']` into a type like `"someValue" | "otherValue"`.

In order to not have typescript read the type as `string`, you will have to define the enum values as readonly by using the const keyword `['someValue', 'otherValue'] as const`. I believe that will turn them into string literals.

Okay, just tried it out. Here's some code to get you started. The comments are the types that are returned when hovering over the const or type in VSCode. You can see that without the `as const` it doesn't work.

```ts
const arrayOfString = ["alpha", "bravo"]
// string[]

const arrayOfLiterals = ["alpha", "bravo"] as const
// readonly ["alpha", "bravo"]

type EnumOfLiterals<T extends readonly string[]> = {
  [I in keyof T]: T[I]
}[number]

type EnumOfAlphaBravo = EnumOfLiterals<typeof arrayOfLiterals>
// "alpha" | "bravo"
```

**Comment by jonavila** [comment]
Thanks @thesunny. Yeah, I'll continue to mess around with it. I'm trying to get it to work as a valid SchemaValue

**Comment by thesunny** [comment]
@jonavila, @ianstormtaylor 

I got custom types working so I thought I'd post.

The syntax is like this:

```ts
  describe("custom date", () => {
    const struct = typedSuperstruct({
      types: {
        date(value: Date) {
          return value instanceof Date
        },
      },
    })

    const Article = struct({ title: "string", date: "date" })

    it("should pass a date", async () => {
      const article = Article({ title: "Welcome", date: new Date(100) })
    })

    it("should fail a date", async () => {
      expect(() => Article({ title: "Welcome", date: 100 })).toThrow(
        /expected.*date/i
      )
    })
  })
```

So in the example above, you'll notice the date type function is defined as taking a `Date` argument. At this point, we actually don't know if it's a `Date` yet (i.e. it is actually `unknown`) but we need a way to tell TypeScript that if it passes validation, we should make this a specific type like `Date`.

Felt like this was not great but good enough. I'm open to other suggestions.

Note that my use case was to validate a nested tree and it worked for it and passed through the types correctly.

```ts
import { Validator, struct, superstruct } from "superstruct"
// import { Prettify } from "~/lib/ts-utils"

export type Prettify<T> = T extends Promise<infer V>
  ? Promise<V>
  : T extends infer U
  ? { [K in keyof U]: Prettify<U[K]> }
  : never

export type CustomTypes = { readonly [key: string]: Validator }

export type SchemaValue<C extends CustomTypes> =
  | keyof C
  | "string"
  | "string?"
  | "number"
  | "number?"
  | "boolean"
  | "boolean?"
  | "object"
  | "object?"
  | "array"
  | "array?"
  | ["string" | "number" | "boolean" | "object" | "array" | SchemaObject<C>]
  | SchemaObject<C>

export type SchemaObject<C extends CustomTypes> = {
  [key: string]: SchemaValue<C>
}

type _TypeFromSchemaValue<
  S extends SchemaValue<C>,
  C extends CustomTypes
> = S extends keyof C
  ? Parameters<C[S]>[0]
  : S extends "string"
  ? string
  : S extends "string?"
  ? string | undefined
  : S extends "number"
  ? number
  : S extends "number?"
  ? number | undefined
  : S extends "boolean"
  ? boolean
  : S extends "boolean?"
  ? boolean | undefined
  : S extends "object"
  ? object
  : S extends "object?"
  ? object | undefined
  : S extends "array"
  ? unknown[]
  : S extends "array?"
  ? unknown[] | undefined
  : S extends SchemaObject<C>
  ? _TypeFromSchemaObject<S, C>
  : S extends [infer T]
  ? T extends SchemaValue<C>
    ? _TypeFromSchemaValue<T, C>[]
    : never
  : never

type _TypeFromSchemaObject<S extends SchemaObject<C>, C extends CustomTypes> = {
  [K in keyof S]: _TypeFromSchemaValue<S[K], C>
}

export type TypeFromSchemaValue<
  S extends SchemaValue<C>,
  C extends CustomTypes
> = Prettify<_TypeFromSchemaValue<S, C>>

export type TypeFromSchemaObject<
  S extends SchemaObject<C>,
  C extends CustomTypes
> = Prettify<_TypeFromSchemaObject<S, C>>

export function typedStruct<S extends SchemaValue<{}>>(
  schema: S
): ((value: unknown) => TypeFromSchemaValue<S, {}>) & {
  test: (value: unknown) => boolean
} {
  const validate = struct(schema)
  return validate as any
}

export function typedSuperstruct<
  C extends Record<string, Validator>
>(settings: { types: C }) {
  return superstruct(settings) as <S extends SchemaValue<C>>(
    schema: S
  ) => (value: unknown) => TypeFromSchemaValue<S, C>
}
```

**Comment by jonavila** [comment]
@thesunny Where is `TypeFromSchemaObject` used?

Also, I'm trying to follow why Prettify is needed. Looks like it checks for a Promise type. I'm trying to figure out where that is applicable

**Comment by thesunny** [comment]
@jonavila 

You can remove `Prettify` and get the same functionality. Based on an infinite nesting bug I found recently with recursive types, I've recently removed `Prettify` from my code and recommend you do so as well. Its purpose was to make type output more readable. I know how to fix it and may do so later.

`TypeFromSchemaObject` is useful as an export. My use case for it is that when I create an API method, I define them like:

```ts
const myAPIMethod = API.method({id: 'number', name: 'string'}, ({ id, name }) => {
  // ...handling in here
})
```

I use `TypeFromSchemaObject` to convert the `{id: 'number', name: 'string'}` into a type. I then plug that type into the following function call so I don't have to declare the types twice and I get type-checking on API methods which are inherently unsafe.

BTW, I have end to end typing on my API. When I make API calls from the client, it finds the right file, the right method, and plugs in the method call signature into the client call signature and then plugs the return types into the client call results.

**Comment by shellscape** [comment]
I've taken a different route to this and written a TypeScript transform plugin that exports a `superstruct<T>` method. The plugin itself will transform that method and interface type and automatically generate a superstruct schema from the interface. So it pretty much takes all of the worry away from type checking the schemas.

Will be released in the coming weeks.

**Comment by ianstormtaylor** [comment]
The latest release has much better TypeScript support, specifically:

- Since struct definitions aren't string-based, you'll ensure that you're writing proper definitions easily with regular compile-time checking.

- And now there will also be compile-time checking of the validations themselves (using TypeScript guards). So for example you can use `if(is(data, User)) { ... }` and have type safety inside the if block—and the same goes for `assert`.

**Comment by Aadmaa** [comment]
For folks reading this later, StructType is now called Infer, used like this: Infer<typeof YourStructObject>
It works great.
