### ISSUE TITLE
[CRITICAL] Unable to import superstruct

### ISSUE THREAD

**Issue by Azarattum** [ianstormtaylor/superstruct#1147]
Since the release `1.0.0` all imports of the library have broken.

## Reporoduction

- `npm install --save superstruct`
- Paste the example from docs
```ts
import { object, string, number } from "superstruct";

const User = object({
  id: number(),
  name: string(),
});
```
- Observe the error
![image](https://user-images.githubusercontent.com/43073346/202531220-1b8a3a1b-cf3a-43c7-abe3-402edddcb643.png)
![image](https://user-images.githubusercontent.com/43073346/202531481-3ef00482-791e-413e-9617-9c89926fb2d8.png)

## Note
https://github.com/ianstormtaylor/superstruct/commit/a7db1f9d771e66e9b3cf8ab62115dda69dcddb60 probably related. The package.json now says:
```json
  "exports": {
    ".": {
      "import": "./vite/superstruct.js",
      "require": "./vite/superstruct.cjs",
      "types": "./lib/index.d.ts"
    }
  },
```
However, there is no `vite` directory in `superstruct` folder:
![image](https://user-images.githubusercontent.com/43073346/202532104-71780f68-d950-4345-8419-8738a65921f2.png)

**Comment by ianstormtaylor** [comment]
Well, I majorly butchered that, sorry @Azarattum. I was migrating a few different packages at once and couldn't keep the configuration right in my head. Should be fixed now in `1.0.3`.
