### ISSUE TITLE
Example coercion does not work. Have I done it right ?

### ISSUE THREAD

**Issue by houd1ni** [ianstormtaylor/superstruct#1175]
Hi!

I read: https://docs.superstructjs.org/api-reference/coercions#custom-coercions
I do:

```typescript
const schema = object({
  x: coerce(number(), string(), (value) => +value)
})
console.log(schema.validate({x: '42'}))
```

I have:

```
[
   StructError: At path: x -- Expected a number, but received: "42",
   value: '42',
   type: 'number',
   refinement: undefined,
   key: 'x',
   path: [ 'x' ],
   branch: [ [Object], '42' ],
   failures: [Function (anonymous)]
 },
 undefined
]

```

What's wrong ? Thanx.

**Comment by JoniJnm** [comment]
You have to use [create](https://docs.superstructjs.org/api-reference/core#create) or [mask](https://docs.superstructjs.org/api-reference/core#mask) to apply coerce functions:

```ts
const schema = object({
  x: coerce(number(), string(), value => +value),
});
console.log(schema.create({x: '42'}));
```

**Comment by houd1ni** [comment]
Thanks! Almost at the same time found it in the code tho 😄 . Obviously, needs some doc improvement for this. @ianstormtaylor
