### ISSUE TITLE
Does "create" supports "passthrough"

### ISSUE THREAD

**Issue by Bonjour123** [ianstormtaylor/superstruct#1233]
When using Superstruct for data coercion, can I allow other non-defined fields ? Same as zod's [passthrough](https://zod.dev/?id=passthrough) method.

**Comment by yeoffrey** [comment]
I would use `type` here.

```typescript
const myStruct = type({ name: string() })

const data = {
  name: 'yeoffrey',
  age: 23,
}

assert(data, myStruct) // Passes
```

**Comment by arturmuller** [comment]
I'm closing this as @yeoffrey seems to have answered the question.

@Bonjour123 if you have any more detail about this or further questions, please head over to our newly opened GitHub Discussions page — we'll be happy to help you out there! :)
