### ISSUE TITLE
Create predefined JS object from Schema

### ISSUE THREAD

**Issue by michalCapo** [ianstormtaylor/superstruct#1239]
This should be as core functionality. Function make should create JS object with default values given by schema.

```
const Some = object({
  age: number(),
  name: string(),
  list: array(string()),
})

const obj = Some.make()

assert(obj.age === Infinity)
assert(obj.name === "")
assert(obj.list.length === 0)

```

**Comment by yeoffrey** [comment]
Hey @michalCapo 👋 

For a feature request, please add some more information. For example, this could end up being a bit weird. Do structs have default values, why should a string default to `""`? I think theres some extra details that would need to be ironed out, but in general I support this idea.

**Comment by yeoffrey** [comment]
Thanks for the info! Do you mind bring this convo into the discussions area? As we work on pruning some of the issues, we've decided that feature requests should end up in the discussion board. Then we can go from there?

**Comment by michalCapo** [comment]
OK, what i need to do?

**Comment by yeoffrey** [comment]
Just go [here](https://github.com/ianstormtaylor/superstruct/discussions) and open a discussion item with the type `idea`. 

<img width="333" alt="image" src="https://github.com/ianstormtaylor/superstruct/assets/50647335/c6b23eea-ce4b-400e-a96e-f52ee384ee3b">
