### ISSUE TITLE
How to validate a string with maximum length?

### ISSUE THREAD

**Issue by christhomas** [ianstormtaylor/superstruct#127]
It's an obvious problem but for some reason this isn't in the manual. How to validate something is a string, with all it's subtle needs, but has a maximum length? 

Seems a really basic one. But I can't see any example how it would work, I can't do a `'string' && value.length < 255` cause that wouldn't work. So how to do a validation which takes a primary type and adds optional extras to it?

**Comment by krstffr** [comment]
I've never used this package, but from looking at the readme file just create a custom data type which checks for both typeof string and length < 255?

It in this section of the readme:
```
import { superstruct } from 'superstruct'
import isUuid from 'is-uuid'
import isEmail from 'is-email'

const struct = superstruct({
  types: {
    uuid: value => isUuid.v4(value),
    email: value => isEmail(value) && value.length < 256,
  },
})
```

**Comment by ianstormtaylor** [comment]
@christhomas Superstruct opts to have the types all defined upfront in a single place. So you'd model it like @krstffr by adding the length check to whatever your custom type is.

This is different from other libraries that encourage writing one-off validators inline by composing a bunch of smaller validations together. But this is by design.

**Comment by aphofstede** [comment]
The newish “size” type could help maybe? 
Something like:
`{ myStringField: “string? & size<1,64>” }`
Would be nice to have

**Comment by TheDirigible** [comment]
This works:
struct.intersection(['string', struct.size([4, 200])]),
Although it's really clunky.  A shorthand would definitely be nice.

IMHO this is a really essential feature.  There are many models with one-off field sizes and nobody wants to basically define schema in 2 places, and then have to maintain a bunch of single-use types.

**Comment by ianstormtaylor** [comment]
This is solved in the newest release with "refinements", specifically the `length` refinement, used like:

```ts
import { string, length } from 'superstruct'

const ShortString = length(string(), 1, 9)
```

And `length` works with the `array` struct too.

**Comment by CalebLovell** [comment]
in case anyone else stubbles across this thread like I did, length is now size. :)
