### ISSUE TITLE
How to validate a not-empty list?

### ISSUE THREAD

**Issue by jormaechea** [ianstormtaylor/superstruct#129]
I need to validate a field that should be a not empty array of some custom type. Example:
```js
const User = struct({
	firstname: 'string',
	lastname: 'string'
});

const Struct = struct({
	myProp: struct.list([User])
});

const validData = {
	myProp: [{
		firstname: 'John',
		lastname: 'Doe'
	}]
};

const invalidData = {
	myProp: []
};

// This is fine
console.log(Struct(validData));

// This should fail
console.log(Struct(invalidData));
```

Is there a native way to do this?

**Comment by ianstormtaylor** [comment]
Hey @jormaechea, there's no out of the box way to do this right now, since the `list` struct is equivalent to an `.every()` call.

**Comment by jormaechea** [comment]
@ianstormtaylor would you be interested in adding the improvement/feature label?
I'd certainly make a PR for this :smile:

**Comment by ericdmoore** [comment]
@jormaechea what type of syntax would you propose? the "empty array fails" seems like a legit use case, what API would you expose to users?

**Comment by ericdmoore** [comment]
nvm I checked out the PR. Sorry to quick on the `Comment` clicking
