### ISSUE TITLE
clerical mistake (doc)

### ISSUE THREAD

**Issue by donotlb** [ianstormtaylor/superstruct#136]
I think the example code in [API Reference#Custom Types](https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#custom-types) have a clerical mistake

```javascript
const User = struct({
  id: 'uuid',
  name: 'string',
  email: 'email',
  age: 30,
  is_admin: 'boolean?',
})
```

should be 

```javascript
const User = struct({
  id: 'uuid',
  name: 'string',
  email: 'email',
  age: 'age',
  is_admin: 'boolean?',
})
```

by the way, thanks for you and your superstruct

**Comment by ianstormtaylor** [comment]
I think this is fixed now in the rewrite to TypeScript, thanks @donotlb!
