### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by gbouteiller** [ianstormtaylor/superstruct#140]
Hello and first of all, thank you for this great library.
I noticed since the last version that every struct operation has a required "defaults" argument. Is it intentional or due to the new typed version?

**Comment by ianstormtaylor** [comment]
Ah, nope! I forgot that `:any` and `?:any` are different! I'll get a fix out shortly.

**Comment by gbouteiller** [comment]
@ianstormtaylor  thank you for your reactivity and for the awesome library 👍

**Comment by ianstormtaylor** [comment]
@gbouteiller okay this should be fixed in `0.8.1`, thanks for reporting!
