### ISSUE TITLE
`error` field has no attributes { path, reason, value}

### ISSUE THREAD

**Issue by iamsaksham** [ianstormtaylor/superstruct#141]
Earlier before the update v0.8.0 the below code had values { path, reason, values }, but now all these values are undefined. Something related to the update

```
import isEmail from 'is-email';
import { parse, isValidNumber } from 'libphonenumber-js';
const { superstruct } = Superstruct; // eslint-disable-line no-undef

const struct = superstruct({
  types: {
    youdian: (value) => {
      if (isEmail(value) || isValidNumber(parse(value))) {
        return true;
      }

      return 'youdian_invalid';
    },
    password: (value) => {
      if (/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{8,})/.test(value)) {
        return true;
      }

      return 'password_invalid';
    },
  },
});

const Credential = struct({
  youdian: 'youdian',
  password: 'password',
});

export function validate(values) {
  try {
    Credential(values.toJS());
  } catch (error) {
    const { path, value, reason } = error; // path/value/reason are undefined

    return path.reduce((prev, curr) => { // path is undefined
      if (value === undefined) {
        return Object.assign(prev, {
          [curr]: 'required',
        });
      }

      return Object.assign(prev, {
        [curr]: reason,
      });
    }, {});
  }

  return {};
}

```

**Comment by ianstormtaylor** [comment]
Hey @iamsaksham, thanks for reporting this! It should definitely have `path` and `value` defined, so something is broken here I think.

The `reason` special-cased logic from before was removed, so you can no longer return strings from the validator functions. Instead you can return objects with a `reason` property like:

```js
youdian: (value) => {
  if (isEmail(value) || isValidNumber(parse(value))) {
    return true;
  }

  return { reason: 'youdian_invalid' };
}
```

This was just to remove a little complexity. You don't have to call it `reason`, you can call it whatever you want. And any properties you return should be mixed into the error. (Assuming whatever's going wrong here is fixed.)

**Comment by iamsaksham** [comment]
@ianstormtaylor thanks for replying man, I think breaking changes should be released with a major version bump, but I can see that it is still in `0.` so thats okay I think.
I'm sticking to version 0.7.0 for now till this is fixed.

Also do let me know If I can help in resolving this. Please guide me to the `getting started` stuff to contribute to this repo.

**Comment by pbarbiero** [comment]
@ianstormtaylor 

> And any properties you return should be mixed into the error

If I mark a custom type optional and return an object, its ignoring my additional properties. Should I open a separate ticket for that, or do you feel its related to this.

**Comment by ianstormtaylor** [comment]
@pbarbiero probably a separate ticket. I wasn't able to reproduce this one quickly and and not currently working on it. But if other's find a clear reproducible issue feel free to open issues!

**Comment by hongkongkiwi** [comment]
I'm having the same issue, easily reproducible. Simply use your above example, but use this:
```
const Credential = struct({
  youdian: 'youdian?',
  password: 'password?',
});
```

This overrides the error message and causes the complaint above.

**Comment by ianstormtaylor** [comment]
I believe this issue no longer exists in the latest `0.10` release. But if you run into this again feel free to open a new issue.
