### ISSUE TITLE
Partial doesn't work

### ISSUE THREAD

**Issue by dimitarkolev** [ianstormtaylor/superstruct#151]
When trying to use partial there is always an error:
```_iterator[Symbol.iterator] is not a function```

**Comment by dimitarkolev** [comment]
I just saw that partial has been renamed to pick. Its working ok now.

**Comment by jdolearydl** [comment]
@ianstormtaylor The documentation is out of date and still shows partial
https://www.superstructjs.org/interfaces/superstruct.html#partial
