### ISSUE TITLE
Testing in Jest

### ISSUE THREAD

**Issue by Aadmaa** [ianstormtaylor/superstruct#269]
Importing struct returns "undefined" when using Jest/Create-React-App. What am I doing wrong?

E.g., consider this minimal test:
```typescript
import { struct } from 'superstruct';

const Struct = struct.literal(42);

it('minimal validation', () => {
    expect(Struct(42)).toEqual(42);
})
```
Jest blows up on struct.literal because it finds that struct is undefined: "TypeError: Cannot read property 'literal' of undefined". I'm using superstruct 0.8.3. 

I can import other installed libraries and test without blowing up. E.g., this works fine:

```typescript
import { v4 } from 'uuid';

const myUuid = v4();

it('minimal validation', () => {
    expect(v4()).toHaveLength(36);
})
```

**Comment by radum** [comment]
I have a different error when using within a Jest test.

```
import { struct } from 'superstruct';

test('test', () => {
  const customerRolesStruct = struct({
    id: 'number',
    name: 'string',
    items: ['string'],
  });

  let valid = false;
  try {
    customerRolesStruct(objWithData);
    valid = true;
  } catch (e) {
    valid = false;
  }

  expect(valid).toBeTruthy();
});
```

And the error I get is:

```
TypeError: (0 , _superstruct.struct) is not a function
```

And if I debug and console log `struct` I get `undefined`.

I am using Node v10.

**Comment by Aadmaa** [comment]
Actually it's the same issue- 'struct' is undefined.

**Comment by radum** [comment]
If you `import { struct } from 'superstruct/lib/index.js';` will work ok.

**Comment by Aadmaa** [comment]
That works! Thx Radu. Closing.
