### ISSUE TITLE
how to use mix max options with array

### ISSUE THREAD

**Issue by artyil** [ianstormtaylor/superstruct#314]
HI, 
from the docs - https://www.superstructjs.org/interfaces/superstruct.html#array

> Array structs validate that their input is an array with elements that match a specific struct. You can also pass the `max` or `min` options to validate the length of the array.

According to above - there are `min` / `max` options available while defining an array validation, but it is not trivial from the docs how to use it. 

Can one kindly provide a working example? How can I validate that the array length is in specific range?

I found the following way will work:
```js
struct.intersection([['number'],struct.size([1,3])])
```

But it doesn't comply with the docs, so I still wonder how to use `min` `max` to make it much simpler?

Thanks!

**Comment by ianstormtaylor** [comment]
This is solved in the newest release with "refinements", specifically the `length` refinement, used like:

```ts
import { array, length } from 'superstruct'

const ShortArray = length(array(number), 1, 9)
```

And `length` works with the `string` struct too.
