### ISSUE TITLE
Release latest code

### ISSUE THREAD

**Issue by abbyhuisman-rw** [ianstormtaylor/superstruct#319]
A project I work on uses Superstruct and we keep getting pinged that there is a security vulnerability in the version of `kind-of`. It looks like Dependabot updated the version within the project and we just need a new release: https://github.com/ianstormtaylor/superstruct/commit/896056fc688f001a3ebd0a158ef4d045b0935dc2

Would you mind releasing the next version?

**Comment by ianstormtaylor** [comment]
Sorry for the delay, just published a new version with those changes included!
