### ISSUE TITLE
Do you think `tcomb` has one or more of your concerns exposed under "Why?"

### ISSUE THREAD

**Issue by fernandocanizo** [ianstormtaylor/superstruct#32]
Hello, this is not an issue, but a question to discuss a little bit.

Have you met [tcomb](https://github.com/gcanti/tcomb) from Giulio Canti?

I wonder if it doesn't addresses all your concerns from this project README or if you considered it but noticed another short-coming or anything that made you start your own project.

**Comment by ianstormtaylor** [comment]
Hey @fernandocanizo, great question. Check out my answer in https://github.com/ianstormtaylor/superstruct/issues/15. Thanks!

**Comment by fernandocanizo** [comment]
Thanks for pointing me there and for that elaborated answer on #15. Sorry I didn't searched well before posting: it seems I forgot to remove `is:open` filter when I searched.

**Comment by ianstormtaylor** [comment]
No worries @fernandocanizo!
