### ISSUE TITLE
Superstruct with React Hook Form

### ISSUE THREAD

**Issue by bluebill1049** [ianstormtaylor/superstruct#337]
Hi there,

My name is Bill, I am the author of React Hook Form. We are working towards version 6  and would love to support superstructure and prompt the simplify and size of this lib. 

Here is a PR: https://github.com/react-hook-form/react-hook-form-resolvers/pull/3

a quick question: as far as I know this lib doesn't support error message in the schema right?

**Comment by ianstormtaylor** [comment]
Hey @bluebill1049, you can mix in custom properties to error if that's what you mean, I'm not totally sure.
