### ISSUE TITLE
New superstruct documentation lack good explanation

### ISSUE THREAD

**Issue by wizardpisces** [ianstormtaylor/superstruct#354]
Example:

type lazy: there is barely any explanation but just simple api ( no more example, cannot understand why discard previous good examples )

As with almost all the complex types, only simple api exists, these simple explanation is not user friendly, new user may ditch this project by this

As far as I know, older versions had documentation far better than this, why the higher version the bad documents

**Comment by clibu** [comment]
+1 I haven't seen earlier documentation, but the current docs are definitely lacking in substance.

**Comment by ianstormtaylor** [comment]
Totally agreed. The newer docs are auto-generated, I was hoping to avoid having to duplicate a bunch of stuff, but they are not as good as the old ones. I think reverting to the old is a good idea, hopefully soon.

**Comment by ianstormtaylor** [comment]
Brought back the old-style docs with improvements in the latest release.
