### ISSUE TITLE
It had to be said. This is so good. Thank you.

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/superstruct#364]
Sorry, I know this isn't an issue and you can close this immediately but I think it had to be said:

These changes are just so so good. Thank you for this upgrade. It is fantastic.

I started to write a new validation library yesterday (literally) because superstruct couldn't handle the cases I needed and the goal was to validate and type anything TypeScript could. This release solves everything and it uses the same semantics and principles as a validation library I wrote pre-my-use-of-TypeScript so it is familiar to use.

Anyways, thank you so much. This work is really good.

**Comment by ianstormtaylor** [comment]
Thanks @thesunny! Very glad to hear it 😄
