### ISSUE TITLE
optional() does not create an optional property on an object

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/superstruct#375]
`optional` does not create an optional property on an object. It should create an optional property in order to match with TypeScript validation semantics.

```ts
const CustomText = object({
  name: string()
  age: optional(number())
})

// creates  a type like:
type UserType = {
  name: string
  age: number | undefined
}

// But it should create a type like this:
type UserType = {
  name: string
  age?: number | undefined
}
```

## Alignment with TypeScript

The Superstruct type does not align with the TypeScript type it is returning.

As an example, this passes Superstruct validation:

```ts
describe("content-types", () => {
  it("should validate content-types", async () => {
    const User = object({
      name: string(),
      age: optional(number()),
    })
    assert({ name: "john" }, User)
  })
})
```

but fails the type `number | undefined` returned by Superstruct:

![image](https://user-images.githubusercontent.com/469587/84109667-0fb87b80-a9d8-11ea-90d2-8edda98e88fd.png)

The red squiggles indicate the following error when hovered:

![image](https://user-images.githubusercontent.com/469587/84109927-af760980-a9d8-11ea-8014-782befc67ebf.png)

## Use case

My use case is that I want to validate slate data types.

They are defined such that the `bold` property is optional. To be specific, they are `optional(literal(true)`. In order to make sure my validations line up against my type definitions exactly, I use unit testing to make sure the two type are equal. Because the optional types show up as a union of the passed in type and undefined but do not add the `?` to the property, they do not match and fail tests.

**Comment by ianstormtaylor** [comment]
Ah interesting, that's unfortunate. I didn't actually realize they were treated differently, but I agree that it should support the `prop?:` use case. Would you be down to make a PR?

**Comment by thesunny** [comment]
Hi Ian, yes I can make a PR though not sure the timeline.

Unfortunately, the lift will be a little hacky in that anything that has a union with `undefined` will become optional. Pragmatically, this appears to be the way SuperStruct works.

FYI, it is impossible to get optional types strictly correct due to this limitation of TypeScript https://github.com/microsoft/TypeScript/issues/13195

**Comment by ianstormtaylor** [comment]
@thesunny was just running into this myself. I'm not sure there is a way to pull up the optionality with TypeScript, but if there is I'd be open to it.

But I did realize a workaround we can use:

```ts
export const Text = intersection([
  object({
    text: string(),
  }),
  partial({
    bold: literal(true),
  }),
])
```

**Comment by thesunny** [comment]
Oh nice!

To clarify my last post, we can turn all values that have union with `undefined` into optional `?` properties something like this:

```ts
type 
```

**Comment by thesunny** [comment]
Oh nice! Thanks for sharing that.

To clarify my previous post, there is a way to do it by turning all unions with `undefined` into `?` optional properties. We `pick` all the properties that extend `undefined` and then recreate them with `?`. We then intersect them with the rest of the properties.

**Comment by ianstormtaylor** [comment]
Ah interesting, that seems like a decent trade off I think. Seems pretty rare that you’d explicitly want a defined `undefined` value to me.

**Comment by JakeElder** [comment]
I just ran in to this issue, thank you for the workaround.

Is it likely your proposed solution will make it in @thesunny? The workaround is fine, but it would be nice to be able to avoid the extra clutter in the struct definition and resulting typescript def.

![image](https://user-images.githubusercontent.com/1167624/84979102-d1018e80-b158-11ea-95b3-83ed1689360e.png)

![image](https://user-images.githubusercontent.com/1167624/84979153-ed053000-b158-11ea-8170-ac35b7093736.png)

Loving your work on Superstruct, it's a joy to use.

**Comment by thesunny** [comment]
@JakeElder @ianstormtaylor 

This now has a PR: https://github.com/ianstormtaylor/superstruct/pull/390
