### ISSUE TITLE
Consider adding string shortcuts to methods without arguments

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/superstruct#376]
Currently, SuperStruct requires all validations to be passed in as functions.

![image](https://user-images.githubusercontent.com/469587/84175912-7c159800-aa35-11ea-9053-e6bdf4cf65aa.png)

This simplifies code (everything is a function) at the expense of some helpful syntax highlighting.

One thing I miss about old SuperStruct was that the syntax highlighting helped you see types.

One way to get the benefit back without breaking simplicity is to allow strings to be used as shortcuts to functions that don't take arguments like `string()` and `number()`. These would have shortcuts like `"string"` and `"number"`. The rule is any method that can be called without an argument can be replaced with its name as a string.

![image](https://user-images.githubusercontent.com/469587/84175967-8fc0fe80-aa35-11ea-99ae-5b3a9a0315ed.png)

Another benefit is it simplifies migration to the latest superstruct from older versions.

**Comment by ianstormtaylor** [comment]
I agree that it helps in terms of looking and seeing the types, but I'm not sure it's worth it given that it would add complexity to the internals of how the validators are created, and how the typings are inferred.

Also, the nice thing about the existing setup is that non-core structs can still be defined in ways that look exactly the same, eg:

```ts
const email = () => struct('Email', isEmail)

const User = object({
  name: string(),
  email: email()
})
```

But if we were to allow strings for some of the core types it would make that parallelism awkward.

Given all that, I think I'm a no on this one, so I'm going to close. But if you think of more arguments along this line feel free to keep commenting or open a new one too.

Thanks!
