### ISSUE TITLE
Consider adding example with import *

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/superstruct#377]
I mentioned that I had a validation library with the same semantics as this new superstruct.

The one difference was that every method hung off an object which I called `be`.

One benefit was that you only imported one variable. For example:

```ts
import be from "~/lib/be"

const User = be.object({
  name: be.string(),
  age: be.optional(be.number()),
})
```

You can get the same benefits to superstruct with:

```ts
import * as be from "superstruct"

const User = be.object({
  name: be.string(),
  age: be.optional(be.number()),
})
```

I wonder if it might be worthwhile to add this as an alternate usage style to the documentation for users that find importing each function separately is a point of friction.

**Comment by ianstormtaylor** [comment]
That sounds good to me, can go in the guide part of the docs right at the beginning where it talks about importing I think?
