### ISSUE TITLE
Add documentation for adding TypeScript type to a custom type

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/superstruct#379]
SuperStruct is able to return the proper typing information for a custom type but the documentation does not indicate how to do this.

Currently the documentation shows this:

```ts
const Email = struct('Email', isEmail)
```

Augment the documentation to show generics, possibly as a second example for TypeScript users only so as not to confuse JavaScript users:

```ts
const Email = struct<string>('Email', isEmail)
```

**Comment by thesunny** [comment]
Hi @ianstormtaylor,

I will PR most of these when I have time.

**Comment by ianstormtaylor** [comment]
@thesunny nice, that would be great!

I think maybe there should be an additional section in the guide called something like "Using TypeScript" and it would have these kinds of things. The other one is the `StructType` inferring utility.

**Comment by thesunny** [comment]
PR https://github.com/ianstormtaylor/superstruct/pull/393
