### ISSUE TITLE
should `is` narrow union types?

### ISSUE THREAD

**Issue by esclapes** [ianstormtaylor/superstruct#381]
Hey there! First of all, thanks for this module. I find the API very enjoyable.

I just bumped into an unexpected behaviour with `is` and type narrowing. 

I couldn't figure out how to reproduce this behaviour in a test, so I am sharing here an example that illustrates the issue. 

```TypeScript
// this is one of the possible inputs for the function, to find and account by id
const byAccountId = object({
  id: string(),
})

// or you could also find it by email
const byEmail = object({
  email: string(),
})

// the imput arguments are defined as the union of both options
export const findAccountArgs = union([byAccountId, byEmail])

// and we type the method accordingly
export function findAccount(args: StructType<typeof findAccountArgs>) {
  let account
  if (is(args, byAccountId)) {
    // --> I would expect args to be narrowed to { id }, but it's still the union
    account = Accounts.findById(args.id)
  }

  if (is(args, byEmail)) {
    // --> and the same happens here, there is no error using args.id here
    account = Accounts.findByEmail(args.id)
  }

  return account ?? null
}
```

Is this expected? Maybe I am missing something about TypeScript and type narrowing. :man_shrugging: 

Thanks in advance.

**Comment by ianstormtaylor** [comment]
Hey @esclapes thanks for catching this. The type inference for `union()` was incorrectly inferring it as an intersection instead. I've just released a new patch which should fix this for you.

**Comment by esclapes** [comment]
Thanks so much!
