### ISSUE TITLE
`e.failures is not iterable` when trying to access failures

### ISSUE THREAD

**Issue by chrisvariety** [ianstormtaylor/superstruct#389]
superstruct version: 0.10.11
node version: 12.17.0

I'm struggling to access `failures` and hoping someone here could help out... 

```js
const { object, assert, string } = require('superstruct');

const User = object({
  firstName: string(),
  lastName: string()
});

try {
  assert({}, User);
} catch (e) {
  for (const failure of e.failures) {
    console.log('failure', failure);
  }
}
```

Result: `TypeError: e.failures is not iterable`

How can I get an actual array of failures? It looks like it's a generator of some sorts.

**Comment by ianstormtaylor** [comment]
Hey @chrisvariety! You should be able to get it using:

```ts
for (const failure of e.failures()) {
  ...
}
```

It's a generator function, because the failures are actually lazy-loaded. So at the time the error is thrown only the first failure is known, and then once you iterate the failures the others are discovered. This way the whole tree of data doesn't need to be walked to return the first failure for performance.

**Comment by chrisvariety** [comment]
@ianstormtaylor Thanks, I was so close 🙈  that works great.

**Comment by sosnail** [comment]
@ianstormtaylor 

how to get information for all of the failures.

**Comment by ianstormtaylor** [comment]
@sosnail just read this thead.

**Comment by sosnail** [comment]
@ianstormtaylor 

```
const User = object({
  firstName: string(),
  lastName: string()
});

try {
  assert({}, User);
} catch (e) {
  for (const failure of e.failures()) {
    console.log('failure', failure);
  }
}
// output 
 failure {
    value: undefined,
    type: 'string',
    path: [ 'firstName' ],
    branch: [ {}, undefined ]
  }
 but I want to get `firstName` and `lastName`  fields.
```

**Comment by rossholdway** [comment]
Am I missing somethign or is this a bug? As @sosnail mentioned, I only ever get back the first error when using `error.failures()` (using the latest release, v0.10.11).

I'd expect 2 errors from the below... 

```javascript
const Article = object({
  id: number(),
  title: number()
})

const data = {
  id: 'a string',
  title: 'also a string'
}

const [error, article] = validate(data, Article);

for(const failure of error.failures()) {
  console.log(failure);
}

// Output
// {
//   value: 'a string',
//   type: 'number',
//   path: [ 'id' ],
//   branch: [ { id: 'a string', title: 'also a string' }, 'a string' ]
// }
```

**Comment by ianstormtaylor** [comment]
Uhoh, sounds like a bug. Can one of you open another issue for it and I’ll check it out? Thanks!

**Comment by rossholdway** [comment]
Thanks @ianstormtaylor. See Issue #394
