### ISSUE TITLE
Multiple types for a field?

### ISSUE THREAD

**Issue by albertgronholm** [ianstormtaylor/superstruct#403]
In 0.8 I could define multiple types for a field. For example:
```
const User = struct.object({
  name: 'string',
  age: 'number | null',
})
```

Is this supported in 0.10 in any way or do I have to create custom types for each and every one of the combinations I need?

**Comment by ianstormtaylor** [comment]
@albertgronholm you can do this using `union`. The old `"x | y"` string syntax actually just used `union` under the covers. Your example would now look like:

```ts
const User = object({
  name: string()
  age: union([number(), null()]),
})
```

But there is also `nullable` now which makes this common use case easier:

```ts
const User = object({
  name: string(),
  age: nullable(number()),
})
```

**Comment by albertgronholm** [comment]
Thanks for the quick answer and sorry for the dumb question!
