### ISSUE TITLE
React native package `main` field related error.

### ISSUE THREAD

**Issue by cmnstmntmn** [ianstormtaylor/superstruct#404]
Hei,

I'm trying to plug supertruct to a react-native app, but i'm getting this error

```
error: Error: While trying to resolve module `superstruct` from file `validation.js`, the package `node_modules/superstruct/package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved (`node_modules/superstruct/index.cjs`. Indeed, none of these files exist:
```

**Comment by cmnstmntmn** [comment]
any workarounds for this ?

**Comment by cmnstmntmn** [comment]
i found [this](https://forums.expo.io/t/sdk-37-cjs-bundler-error-with-superstruct-library/35630)

**Comment by roccomuso** [comment]
any news on this?

**Comment by rhythnic** [comment]
`package.json` is using `type:module`. For recent versions of Node.js, this means that the entrypoint to the module should be an ECMAScript module; however, `main` is set to a CommonJS file.  This makes Superstruct unusable in any Node.js package of `type:module`.  It's possible to support both ECMAScript modules and CommonJS by using the `exports` key.

```
// package.json
{
  // keep pointing main to cjs for legacy versions of node.js
  "main": "./lib/index.cjs",
  // use conditional exports for recent versions of node.js
  "exports": {
    "import": "./lib/index.es.js",
    "require": "./lib/index.cjs"
  },
  "type": "module"
}
```

**Comment by isnifer** [comment]
@rhythnic why did you mention Node.js? The question was about React-Native. Your PR does not help to fix `superstruct` for RN. @ianstormtaylor too early to close this issue.

**Comment by isnifer** [comment]
But this config for metro bundler helped me:
```js
// https://github.com/ioveracker/demo-react-native-emotion/blob/master/metro.config.js

const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
    const {
        resolver: { sourceExts },
    } = await getDefaultConfig();
    return {
        resolver: {
            // Add cjs extension so stylis will load.
            sourceExts: [...sourceExts, 'cjs'],
        },
        transformer: {
            getTransformOptions: async () => ({
                transform: {
                    experimentalImportSupport: false,
                    inlineRequires: false,
                },
            }),
        },
    };
})();
```

**Comment by gabrielgrover** [comment]
I am using expo for my react native project and this worked for me

`
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  resolver: {
    sourceExts: [...defaultConfig.resolver.sourceExts, 'cjs'],
  },
};
`

**Comment by leolangen** [comment]
We have a different version of metro-config in our project, using RN version 0.61.2. The following worked for me

```javascript
...
const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts 

module.exports = {
  ...
  resolver: {
    sourceExts: [...defaultSourceExts, 'cjs'],
    ...
  }
}
```

**Comment by Thanaen** [comment]
Hello !
Question: why was the issue closed? The problem still exists today, just create a new react project and add the package to reproduce it!

**Comment by isnifer** [comment]
@Thanaen man, just read a comment above yours

**Comment by Thanaen** [comment]
> @Thanaen man, just read a comment above yours
Hello @isnifer ,
If we need to modify a react-native configuration file to make the package work, can we consider the issue resolved? 😕

**Comment by isnifer** [comment]
@Thanaen yes. Author just decided to use "standard" extension for non es-modules files.
Anyway, I don't care cause I decided don't use this package

**Comment by matomesc** [comment]
I'm getting the following error after using [the workaround above](https://github.com/ianstormtaylor/superstruct/issues/404#issuecomment-800182972) using react-native 0.69.5 and expo
![image](https://user-images.githubusercontent.com/477723/191607823-17db6e79-9a92-4231-b4ec-a3f77b47c500.png)
