### ISSUE TITLE
Extending structs

### ISSUE THREAD

**Issue by SteveDeWald** [ianstormtaylor/superstruct#410]
Is there an easy way to extend struct objects?  I read through the documentation and couldn't figure out how to do it.  I'd like to write something like this:

```javascript
class A {
    someProp = "";
    static validationStruct = object({ someProp: string() });
}

class B extends A {
    anotherProp = 0;
    static validationStruct = A.validationStruct.extend({ anotherProp: number() });
}

const b = new B();
assert(b, B.validationStruct)
```

Maybe this is an anti-pattern or there's a better way.  Would love any insight you can offer.  Thanks.

**Comment by dhawal1248** [comment]
Hey @SteveDeWald , did you get anything on this?

**Comment by SteveDeWald** [comment]
> Hey @SteveDeWald , did you get anything on this?

I ended up specifying the extended properties directly, e.g.:

```ts
class A {
    someProp = "";
    static validationStructAttrs = { someProp: string() };
}

class B extends A {
    anotherProp = 0;
    static validationStruct = object({ 
        ...A.validationStructAttrs,
        anotherProp: number()
    });
}
```

Not very elegant, but it works fine for my purposes.

**Comment by mikestopcontinues** [comment]
I think instances of `Struct` should expose their schema for this purpose. There's a property for it, but it's completely unused by the `struct()` func, which all of the types use. For now, I only see heavily leveraging dynamic types or conditionals in type-generating functions to be any solution at all, and definitely not an easy one.

**Comment by ianstormtaylor** [comment]
The pull request linked ^^^ adds an `assign` utility for this purpose:

```ts
const a = object({ ... })
const b = object({ ... })
const c = assign([a, b])
```

**Comment by xiaoyu-tamu** [comment]
Hi, @ianstormtaylor. What is the status on that one?

**Comment by ianstormtaylor** [comment]
@xiaoyu-tamu hoping to merge it imminently.
