### ISSUE TITLE
Typescript type fields incorrectly marked as optional

### ISSUE THREAD

**Issue by hpello** [ianstormtaylor/superstruct#411]
Hi,

I would like to report the following behaviour on version 0.10.12.
It seems that superstruct incorrectly infers optional fields on the Typescript derived types, where they should be required. 

The following piece of code should produce an error:

```typescript
// index.ts
import type { StructType } from 'superstruct'
import { object, string } from 'superstruct'

const A = object({
  a: string(),
})

const x: StructType<typeof A> = {}

```

Indeed, the infered type for `StructType<typeof A>` is:
```typescript
{
    a?: string;
}
```

when it should be
```typescript
{
    a: string;
}
```

On 0.10.11, the following message is correctly thrown:

```typescript
src/index.ts:8:7 - error TS2741: Property 'a' is missing in type '{}' but required in type '{ a: string; }'.

8 const x: StructType<typeof A> = {}
        ~

  src/index.ts:5:3
    5   a: string(),
        ~~~~~~~~~~~
    'a' is declared here.
```

Regards,

**Comment by o-alexandrov** [comment]
As @hpello typed above: **there is a degradation after upgrading** from `0.10.11` vs `0.11.12`.
However, on `0.10.11`, even though `StructType` correctly infers `required` attributes, but **is incorrect with optional**s.

<img width="359" alt="Screen Shot 2020-07-15 at 9 32 04 AM" src="https://user-images.githubusercontent.com/9992724/87558221-7a677180-c67e-11ea-8fbf-4d236e32e24e.png">

**Comment by vriad** [comment]
@o-alexandrov Sure this isn't an issue with tsconfig.json? Often you'll see this behavior if the library in question expects `"structNullChecks": true`. I suspect superstruct does (even though it's not documented as such).

**Comment by hpello** [comment]
Good catch! Indeed, with `"strictNullChecks": true` in tsconfig.json, the fields are correctly marked as required 👍 

> `--strictNullChecks` (boolean, false): In strict null checking mode, the `null` and `undefined` values are not in the domain of every type and are only assignable to themselves and `any`

Is this something that should be added to the docs?
