### ISSUE TITLE
length min and max 

### ISSUE THREAD

**Issue by fanshan** [ianstormtaylor/superstruct#424]
Hello,

Is this normal that following code throws an exception?

```js
const s = require('superstruct');

const myStruct = s.length(s.string(), 1, 3);

s.assert('a', myStruct);
```

With the same struct `s.assert('abc', myStruct)` throws exception too. And `s.assert('ab', myStruct)` doen't throw exception.

So do we have to consider that the length of the value (string or array) must be strictly greater than `min` and strictly inferior than `max`?

Maybe the subject has already been discussed, but I didn't find any reference to this.

Thanks.

**Comment by Simonwep** [comment]
Take a look at the [length](https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#length) refinement:
> length enforces that a string or array struct also is **within** a certain min and max length.

That means both `s.assert('a', myStruct);` and `s.assert('abc', myStruct);` are supposed to fail as their character-length is not _between_ `1` and `3`. Only two characters are valid in your case.

**Comment by fanshan** [comment]
Thank you @Simonwep 

This is due to my english understanding... I close.
