### ISSUE TITLE
Return value of validate does not work as expected with TypeScript

### ISSUE THREAD

**Issue by Simonwep** [ianstormtaylor/superstruct#426]
First off, thanks for this library - I love it!
There is a tiny issue thought which is kinda annoying to deal with:
```ts
const [error, value] = validate('abc', string());
if (error) {
    // Handle error
} else {
    value.length; // TS2532: Object is possibly 'undefined'.
}
```

The return value of `validate` is defined as ` [StructError, undefined] | [undefined, T]` which means that in case error is `undefined` the `value` variable shouldn't be right? Is this a typescript limitation or am I missing something here?

Using the return value without array-deconstructing works fine:
```ts
const result = validate('abc', string());
if (result[0]) {
    // Handle error
} else {
    result[1].length; // OK
}
```

Is there a known work-around in this case? Or is this already a known issue with TS (I couldn't find anything about that on SO / GH)?

My Environment:
```
OS: Windows 10 Pro
Node: 12.16.3
SuperStruct: 0.10.12
TS: 3.9.6
```

**Comment by bybrunobarros** [comment]
It's a Typescript matter. At compile time TS can't tell if `value` will be undefined or not. So it raises this error.
There are several ways to solve it.

1. Check value `if (value) value.length`
2. Another way is to use the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) `value!.length`.
3. You could get some inspiration from functional programming and use the same mechanism as the [Either](https://gcanti.github.io/fp-ts/modules/Either.ts.html) data type.

I'd go for 1. :)

**Comment by Simonwep** [comment]
Thanks for the quick response :) I think I'll go with the first one and close this as it's not related to the library😊
