### ISSUE TITLE
Making a struct optional

### ISSUE THREAD

**Issue by mycaule** [ianstormtaylor/superstruct#46]
Hello, if I want to make the author field optional, what do I have to do with this basic piece of code ?

https://github.com/ianstormtaylor/superstruct/blob/07caeb205bffbfc00759381ed84004c0ad4e9c8e/examples/composing-structs.js#L17

```
const Article = struct({
  id: 'number',
  title: 'string',
  created_at: 'date',
  published_at: 'date?',
  author: User,
})
```

What I would like to do is just add the question mark sign.

Thanks.

**Comment by mycaule** [comment]
Found the answer in the unit tests, here is the way to do it:

https://github.com/ianstormtaylor/superstruct/blob/master/test/fixtures/object-lists/property-optional.js#L6

Maybe update the docs.

**Comment by xyclos** [comment]
Simply adding the `?` appears to work:

```
const Article = struct({
  id: 'number',
  title: 'string',
  created_at: 'date',
  published_at: 'date?',
  author: User?,
})
```

**Comment by mycaule** [comment]
The ` | ` syntax should be documented too. It is already implemented.

Example :
```
meta: 'object | null'
```

**Comment by Silic0nS0ldier** [comment]
`struct.union([ 'object', 'null' ]` achieves the same thing, for those following this. Comes in handy when validating more complex objects.

**Comment by mycaule** [comment]
The set of possible operations on `structs` (intersection, union, optional etc..) is already well documented here, except the one char short syntax. Got to be familiar with functional programming to connect the dots.
https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#structs

**Comment by ianstormtaylor** [comment]
Documented now!
