### ISSUE TITLE
`coerce()` should run recursively (and not assert)

### ISSUE THREAD

**Issue by mikestopcontinues** [ianstormtaylor/superstruct#469]
Right now, it's impossible to coerce a nested structure, both because `coerce()` also validates (#467 ) but also because `coerce()` only runs on the top-level object. For instance, `coerce({}, type({...props}))` will fail, even if all props have coercions, because they never run.

`coerce()` should function parallel to `check()` (preferably with a context object). In the case of validate-with-coerce, they could still run like now, in tandem.

**Comment by ianstormtaylor** [comment]
This is solved in #383 by fixing the coercers.

For the case of wanting to just run validation with coercion without asserting you can use `validate(value, Struct, true)` with the last flag toggling coercion. (The existing `coerce` help is renamed to `create` to better convey what it does.)

As for the issue of nesting, that's interesting I hadn't considered it. Can you describe your use case with `type` there instead of `object`? Just because I was thinking of `type` as an "interface" where you don't care about the other properties, so using `coerce/create` with it feels strange. But I'm open to changing it to have more useful coercion behaviors!

**Comment by mikestopcontinues** [comment]
Hey, I wanted to have a chance to look through the new code before I responded to this one. I actually used `type` as a placeholder for any given type above, forgetting there's a `type` type. :) 

Here's my use-case for deep coercion. When a user creates a book, there's a lot more fields than I can reasonably hold at the top level of my db doc. This is a big simplification, but imagine something like this:

```js
const format = defaulted(object({
  asin: defaulted(nullable(string()), null),
  isbn: defaulted(nullable(string()), null),
  price: coerce(nullable(number()), (v) => parseFloat(v.replace('$', ''))),
  storeLinks: defaulted(record(enums(['amazon', 'kobo', 'apple']), string()), {}),
}), {});

const Book = object({
  bookId: string(),
  title: string(),
  ebook: format,
  softcover: format,
  hardcover: format,
  audiobook: format,
});
```

In all likelihood, I won't have complete information at the time this object is created. There's also dozens more fields than I've included here and a lot of valid reasons things can be missing. But I've got to get a stable object into the DB, especially to be able to send updates without querying the entire object first (e.g. `SET audiobook.storeLinks.kobo = [URL]`).

I may be wrong on this, but I think without deep coercion, I basically need another whole set of schemas (a la `castSpec` from #468) to be able to shape the object before validation.

I do realizing it's a pretty substantial refactor though. I took a look a few months ago, and in addition to changing the validation code, it also requires storing the definition (`{k: string(), ...etc}`) of `object`, `array`, etc on the Schema instance to be tree-walked later. Otherwise the coercers would always need to be located on the object definitions rather than on their keys.

Anyway, do you see the value in this?

**Comment by ianstormtaylor** [comment]
@mikestopcontinues I believe with `object` you should get deep coercion now. Does that solve the issue?

Here's a test case I just added to make sure going forward:

```ts
import { defaulted, string, object } from '../../..'

export const Struct = object({
  book: defaulted(
    object({
      title: defaulted(string(), 'Untitled'),
    }),
    {}
  ),
})

export const data = {}

export const output = {
  book: {
    title: 'Untitled',
  },
}

export const create = true
```

**Comment by mikestopcontinues** [comment]
Cool! I'll try it out. Can I get back to you in a few days? I'm just circling back to my API now.

**Comment by ianstormtaylor** [comment]
Added in `0.13.0`!

**Comment by nhagen** [comment]
Is there a technical blocker on using `create` recursively on `type`s?

We are migrating a codebase to typescript and are already invested in superstruct, but as we migrate, we are only migrating fields on data as they're used. So for example, our early PRs might only care about 1-2 fields on an object with 20 fields returned by an API. To keep our PRs clean, I want to only add struct properties to `type`s as those fields are used for the first time in that PR. This way we don't have to have an early PR that makes a bunch of wrong assumptions about data types, refinements, etc, when someone is going to go back and it correctly later anyways when we migrate the feature that actually uses those fields.

Another use case is for deprecated fields. So for example, our backend might return deprecated fields that have poor documentation these days. We'd like to not have them available in our type system, so we prefer `type` to `object` on these data object.

Really, for server data, we _always_ prefer `type` to `object`. But if we can't use `create` with `type`s, we have a major problem.

**Comment by mikestopcontinues** [comment]
@nhagen You can use create with types.

**Comment by nhagen** [comment]
But does it work recursively? I'm running into an issue where its not validating nested structures, resulting in

> Expected the value to satisfy a union of `type | type`, but received: [object Object]"

Not sure if its a bug I should make an example for, or if `create` is not intended to be recursive for `type` objects as mentioned earlier in this thread

**Comment by mikestopcontinues** [comment]
Ah, I'm sorry. I lost the thread a little. I think this probably deserves a bug report. I'd you look at the code, type is definitely supposed to be recursive. I can say I've found union to be a little finicky myself, so I'd be willing to be the problem is there.

**Comment by nhagen** [comment]
Thanks @mikestopcontinues you're right, I checked any `create` works fine for a basic case like
```
  it('should create nested types', () => {
    const S = type({
      hi: defaulted(string(), 'sdf')
    })
    const S2 = type({
      a: string(),
      b: defaulted(S, {})
    })

    let val;
    expect(() => {
      val = create({a:'sdf'}, S2);
    }).not.toThrow();
    expect(val).toEqual({ a: 'sdf', b: {hi: 'sdf'}})
  })
```
I'll dig into the union issue.
