### ISSUE TITLE
What's still missing for a first major version?

### ISSUE THREAD

**Issue by Max-ebay** [ianstormtaylor/superstruct#491]
What's still missing for the first major version? Are there any bigger interface changes planned?

If there would be `1.x` live, we would know if something breaks by updating to another major version. Also automatic updates with NPM or other tools like renovate aren't possible inside of `0.x`.

**Comment by InSuperposition** [comment]
This PR appears to be significant for getting to 1.0.
https://github.com/ianstormtaylor/superstruct/pull/440

**Comment by ianstormtaylor** [comment]
Once https://github.com/ianstormtaylor/superstruct/pull/383 is merged and then given a bit of time to see if it's stable and fixed all of the things it set out to do I'm down to bump to `1.0`.

**Comment by maxadv** [comment]
@ianstormtaylor Is there still something missing? I think it would be worth it to have a major version to track better breaking changes.

**Comment by ianstormtaylor** [comment]
@maxadv good call, just published `1.0. Thanks!

**Comment by maxadv** [comment]
That's great! Thank you very much!
