### ISSUE TITLE
SCRIPT1002 Syntax error for IE11

### ISSUE THREAD

**Issue by Max-ebay** [ianstormtaylor/superstruct#495]
I guess it's probably related to this section inside of the bundle which contains `class`. This isn't supported by IE11 https://caniuse.com/es6-class

```js
class p { ... }
```

As a workaround I will make sure that this dependency runs through babel.

**Comment by Max-ebay** [comment]
I just saw you have babel configured for the UMD bundle: https://github.com/ianstormtaylor/superstruct/blob/master/config/rollup-umd-min.js

I'm not sure what the problem is.

**Comment by ianstormtaylor** [comment]
Hey @Max-ebay I'm not sure either, would need more information, the output is transpiled, but there's a good chance that IE11 is so old that the target is not set far enough back for it. I generally don't support IE11 with my libraries out of the box, but people are free to add extra transpiling steps to get it to work in their own codebases.
