### ISSUE TITLE
make it available for Deno

### ISSUE THREAD

**Issue by hemedani** [ianstormtaylor/superstruct#498]
Please make superstruct available for Deno also in [Deno.land](https://deno.land/x)

**Comment by ianstormtaylor** [comment]
No idea how to do this, but I'm open to someone setting it up.

**Comment by sirikon** [comment]
Hi! I'm trying to use superstruct on Deno and have some input on this:

Currently, superstruct is present in Deno.land -> https://deno.land/x/superstruct. deno.land is just a cache that points to Git repositories containing modules for Deno. In Deno dependencies are not managed by some npm-like package manager. Modules are just HTTPS addresses pointing to code.

superstruct in deno.land is pointing to this repository's `src` folder, but currently it doesn't work. First reason is: imports doesn't include the `.ts` file extension, which is required in Deno.

Also I'm having some issues like these, but that's what I'm currently working on.

```
error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type '{}'.
  Property '[SymbolConstructor.iterator]' does not exist on type '{}'.
  return isObject(x) && typeof x[Symbol.iterator] === 'function'
                               ~~~~~~~~~~~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/utils.ts:9:32

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
        if (struct.schema[key] === undefined) {
            ~~~~~~~~~~~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/utils.ts:142:13

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          delete value[key]
                 ~~~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/utils.ts:143:18

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          value[k] = v
          ~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/utils.ts:178:11

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          yield [key, value[key], schema[key]]
                      ~~~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/structs/types.ts:345:23

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          yield [key, value[key], Never]
                      ~~~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/structs/types.ts:349:23

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          const v = value[k]
                    ~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/structs/types.ts:394:21

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
          yield [k, value[k], schema[k]]
                    ~~~~~~~~
    at file:///home/sirikon/repos/srkbz-genesis/src/kubernetes/defgen/src/vendor/superstruct/structs/types.ts:557:21

Found 8 errors.

```

**Comment by sirikon** [comment]
Update on that: Seems like doing this in every place where it gets an error does the trick, but probably not the best solution. Good enough for my local fork unless it breaks somewhere.

![image](https://user-images.githubusercontent.com/1157382/126685489-db94aba0-e7f1-4023-a9c9-8497b5e872e1.png)

**Comment by sirikon** [comment]
After more testing, I think it works pretty well with the changes mentioned before. Have been using it for a Deno-based project yesterday and worked well.

Fixing the issues so Deno users can use it from deno.land should be straightforward, but making the unit tests work on Deno might require more work.

**Comment by roonie007** [comment]
Missing `.ts` in imports and exports which must be explicitly written

example: 
![image](https://user-images.githubusercontent.com/7860859/147842490-f8ab41a7-cbeb-4ef9-85a6-8130ae1c6c60.png)

**Comment by nsf** [comment]
Also note to deno users: you can use this module via ES module CDNs, e.g.:
```typescript
import * as ss from "https://cdn.skypack.dev/superstruct@0.15.4";

const User = ss.object({
  name: ss.string(),
  age: ss.number(),
});

console.log(ss.validate({name: "john", age: 19}, User));
console.log(ss.validate({name: "john"}, User));


```

**Comment by hemedani** [comment]
@nsf the `cdn.skypack.dev` does not include typescript types

**Comment by nsf** [comment]
@hemedani worked for me with no additional setup in vscode:
![image](https://user-images.githubusercontent.com/12567/160232271-e70782a9-9ab4-4cf2-9064-74db40eb013c.png)

**Comment by hemedani** [comment]
but it's not worked for me
<img width="1454" alt="Screen Shot 1401-01-06 at 13 38 56" src="https://user-images.githubusercontent.com/6236123/160232866-b37f3138-ddb3-4133-8278-d7e81324bdd8.png">

**Comment by hemedani** [comment]
Sorry, I could not get what I meant, I mean it does not include superstruct typescript utils like `Infer`

**Comment by nsf** [comment]
@hemedani hm, yes indeed, in this case I apologize for suggesting a method that doesn't quite work

**Comment by sirikon** [comment]
https://esm.sh/ Works if you need types, they explicitly have Deno support.

Anyone using these random CDNs from the internet, consider using Deno’s locking mechanism to ensure that the dependencies doesn’t change from time to time.

**Comment by hemedani** [comment]
I'm just creating a [clone version of this](https://github.com/MiaadTeam/lestruct) on `deno.land`  : `https://deno.land/x/lestruct`

it just changes a little folder structure and adds some `any` type for eliminates several errors.

in the future maybe I add some additional structure, especially to long files, and add documentation also.

**Comment by hemedani** [comment]
it's worked fine till now

**Comment by arturmuller** [comment]
Superstruct is now available via JSR as [@superstruct/core](https://jsr.io/@superstruct/core), which should make it exceptionally easy to consume in Deno: `deno add @superstruct/core`. :v:
