### ISSUE TITLE
add support for intersection types

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/superstruct#5]
Using the `string & number` syntax.

**Comment by amonsosanz** [comment]
Is there a way to use intersection types with another syntax? Haven't found any example in the docs. I've tried this so far:

```typescript
import * as s from "superstruct";

type Foo = {
  foo: string;
}

type Bar = {
  bar: string;
}

type FooBar = Foo & Bar;

const Foo: s.Describe<Foo> = s.type({
  foo: s.string(),
});

const Bar: s.Describe<Bar> = s.type({
  bar: s.string(),
});

const FooBar: s.Describe<FooBar> = s.intersection([Foo, Bar]);
```

But I'm getting this error:

![image](https://user-images.githubusercontent.com/15896177/133124740-7013f373-636b-4d8b-afde-d4c576cec825.png)

I'm probably doing something wrong, just discovered the lib...

Thx!
