### ISSUE TITLE
Checking if a value is a struct

### ISSUE THREAD

**Issue by amsul** [ianstormtaylor/superstruct#50]
First off, props for the awesome library! Loving it so far 💜 

Only hiccup I've had is there doesn't seem to be a way to tell if a value is a struct or not. There is the one method - but it's private: https://github.com/ianstormtaylor/superstruct/blob/eca567de5ac47debe0a9229d0f75c60afea3c8a4/src/is-struct.js

Is this something you'd be okay with exporting publicly?

**Comment by ianstormtaylor** [comment]
Hey @amsul, yes I'm down to export that. I'd love a PR if you were willing to make one! Thanks.

**Comment by amsul** [comment]
I realized it's more appropriate for my use case to just create a type definition for a struct. So I don't actually need this anymore.
