### ISSUE TITLE
Is the demo jsfiddle still valid?

### ISSUE THREAD

**Issue by frederikhors** [ianstormtaylor/superstruct#504]
Is the [demo](https://github.com/ianstormtaylor/superstruct#demo) jsfiddle still valid?

![image](https://user-images.githubusercontent.com/41120635/96155427-364f6b80-0f10-11eb-9853-beee2e88812b.png)

**Comment by zenflow** [comment]
Nope. I noticed this too when I was first checking out superstruct. The API has changed. I actually refactored the demo to use the updated API, so I could play with it. Unfortunately I didn't save that ☹️ So if you do the same, share with everyone 😄

**Comment by zenflow** [comment]
Here is the demo refactored to use the updated API:

```js
const { object, number, string, assert } = window.Superstruct

const User = object({
  id: number(),
  name: string(),
})

const user = {
  id: 'invalid',
  name: 'Jane Smith',
}

try {
  assert(user, User)
  log('valid', user)
} catch (e) {
  const { message, path, data, type, value } = e
  log('invalid', { message, path, data, type, value })
}

function log(type, data) {
  document.body.className = type
  document.body.textContent = JSON.stringify(data, null, 2)
}
```

**Comment by ianstormtaylor** [comment]
Oops, looks like I updated the screenshot but forgot to update the link. Just fixed!
