### ISSUE TITLE
A custom property with a default value throws an error

### ISSUE THREAD

**Issue by amsul** [ianstormtaylor/superstruct#51]
Me again 🙂 

---

When using a struct as the type for a property, it throws an error even if a default value is specified.

See it in action: https://runkit.com/embed/z10qks2qv2v1

```js
const User = superstruct.struct({
  id: 'number',
  name: 'string',
})

const Article = superstruct.struct({
  id: 'number',
  title: 'string',
  author: User,
}, {
  author: {
    id: 1000,
    name: 'Owner',
  },
})

// Passes as expected
Article({
  id: 1,
  title: 'This works as expected',
  author: {
    id: 2,
    name: 'Contributor',
  },
})

// Fails :(
Article({
  id: 1,
  title: 'This does not work!',
})
```

**Comment by amsul** [comment]
This is actually a pretty edge use-case and I think the right way to handle this is to create a custom type.

The example I've posted is not the best (considering what I'm actually trying to do) and so I think it's safe to ignore this.

**Comment by amsul** [comment]
@ianstormtaylor I *JUST* realized how default values actually work! It's the entire object - rather than by each property.

Which means this doesn't work as I would expect:

```js
const Object = superstruct.struct({
  id: 'number',
  value: 'string',
}, {
  value: 'Dope',
})

const object = Object({ id: 1 })
console.log(object.value) // undefined
```

Not sure if this is what is intended - but it's definitely not what I would expect.

**Comment by ianstormtaylor** [comment]
@amsul you're absolutely right, that was not intended. I thought I had a test case for this but it looks like I didn't and it regressed. I've added a fix, and will release a new version now. Thank you!

**Comment by amsul** [comment]
@ianstormtaylor thank **you**! 🙏
