### ISSUE TITLE
Correct description of partial

### ISSUE THREAD

**Issue by matthias-ccri** [ianstormtaylor/superstruct#524]
The readme describes `partial` with what appears to be an incorrect description.

https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#partial

> partial structs are similar to object structs, but they only require that the specified properties exist, and they don't care about other properties on the object.

It says it "requires that the specified properties exist". But that's not what I'd expect, especially compared to typescript's [built in `Partial`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) where "all properties are optional".

And there's already [`type`](https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#type) which does the same thing as the readme's description of partial.

**Comment by ianstormtaylor** [comment]
Fixed now I believe.
