### ISSUE TITLE
Defaults from function

### ISSUE THREAD

**Issue by ecwyne** [ianstormtaylor/superstruct#53]
The [examples](https://github.com/ianstormtaylor/superstruct/blob/c9294266173a06c12ad648b9fb475e1eb9ce350e/examples/default-values.js#L19) show passing a function to defaults, however when I try to do so I receive the following:

```
TypeError: Expected a value of type `date` for `created_at` but received `() => new Date()`.
```

**Comment by ianstormtaylor** [comment]
Good call @ecwyne, thank you for catching that. Just added a test and published a patch release!

**Comment by ecwyne** [comment]
Thanks for such a quick response @ianstormtaylor!

One other idea I wanted to throw out there (and am happy to open a new issue if that would make more sense) is if it's possible to pass arguments into the `defaults` function. For example:

The original object is passed in...
```javascript
const CardDetails = struct({
  cardNum: 'string',
  last4: 'string'
}, {
  last4: ({cardNum}) => `XXXX${cardNum.substr(cardNum.length - 4)}`
});
```

This is my actual use case. I'm wrapping a credit card API that requires me to provide both of these

**Comment by ianstormtaylor** [comment]
Hey @ecwyne I'm open to the idea! Right now the code for handling the defaults delegates to the lower-level functions, so it doesn't have access to that. But it would probably be a simple change in the `object` struct type. I'd be open to a PR that implements this. Thanks!

**Comment by ianstormtaylor** [comment]
@ecwyne actually in a fun coincidence, I just realized I need this for the thing I'm working on. I've added it now!
