### ISSUE TITLE
`intersection` and `masked` seems doesn't work properly with `object` and `type`

### ISSUE THREAD

**Issue by mojtabast** [ianstormtaylor/superstruct#531]
Hi,

I'm kinda confused by `superstruct` behavior on `intersection` and `masked`. I tried to simplify the problem and create a minimal reproduce. so it's available [here on Codesandbox](https://codesandbox.io/s/superstruct-ff5i4-ff5i4).

here is a sample data & `superstruct`'s types:
```js

let data = {
  id: 1,
  name: "mojtaba",
  addresses: [
    {
      address: "a"
    },
    {
      address: "b"
    }
  ]
};

let user_base_type = {
  name: string()
};

let addresses_base_type = {
  addresses: array(
    object({
      address: string()
    })
  )
};
```

intersection doesn't work when passing two `object`:

```js
let user_type = object(user_base_type);
let addresses_type = object(addresses_base_type);
let full_user_type = intersection([user_type, addresses_type]);

let output = is(data, full_user_type);

console.log(output); // it returns false because 
```

intersection only works when passing `type`

```js
let user_type = type(user_base_type);
let addresses_type = type(addresses_base_type);
let full_user_type = intersection([user_type, addresses_type]);

let output = is(data, full_user_type);

console.log(output); // true
```

`masked` only works with `object`
```js

let output = coerce(data, masked(object(addresses_base_type)));
console.log({ output }); // {addresses: [...]}

```

but `masked` doesn't work with `type`

```js

let output = coerce(data, masked(type(addresses_base_type)));

// TypeError: Expected a value of type `Array<Object<{address}>>` for `addresses` but received `undefined`.
```

so we can not use use intersectioon & masked together. because `intersection` only works with `type` and `masked` only works with `object`.

```js
let output = coerce(
  data,
  masked(intersection([object(user_base_type), object(addresses_base_type)]))
);

// TypeError: Expected a value of type `string` for `name` but received `undefined`.
```

or

```js
let output = coerce(
  data,
  masked(intersection([type(user_base_type), type(addresses_base_type)]))
);

// TypeError: Expected a value of type `string` for `name` but received `undefined`.
```

none of them works.

Am I missing something here?

**Comment by ianstormtaylor** [comment]
Hey @mojtabast in that PR I linked ^^^ there is an `assign` utility added that achieves what I think you're looking for in the intersection/object case. 

Can you open a separate issue for the masking problems? I'm not sure I understand what's going on with that one yet, but it's a little hard to understand since the examples are all intertwined. Thanks!
