### ISSUE TITLE
Optional types still show up as required in TS

### ISSUE THREAD

**Issue by allroundexperts** [ianstormtaylor/superstruct#540]
The types that are inferred should show `?` with the properties that have the `optional` struct. Screenshot attached.

<img width="346" alt="Screenshot 2020-11-21 at 11 15 26 AM" src="https://user-images.githubusercontent.com/30054992/99869229-33205d00-2beb-11eb-937d-1083561e612f.png">

<img width="306" alt="Screenshot 2020-11-21 at 11 15 37 AM" src="https://user-images.githubusercontent.com/30054992/99869230-361b4d80-2beb-11eb-8ca5-f4b66f54ebca.png">

<img width="368" alt="Screenshot 2020-11-21 at 11 16 05 AM" src="https://user-images.githubusercontent.com/30054992/99869231-37e51100-2beb-11eb-877c-4cb753b37e59.png">

In reality, `T` should be:
```
{
  status: string;
  mmToken?: string;
}
```

**Comment by ianstormtaylor** [comment]
Based on the tests here https://github.com/ianstormtaylor/superstruct/blob/master/test/typings/optional.ts it should be working, but if you can provide more information or figure out what's causing the issue that would be great!

**Comment by xiaoyu-tamu** [comment]
Did you enabled strict in tsconfig? That might be the cause

**Comment by theweiweiway** [comment]
Actually, I'm getting this problem too:

<img width="355" alt="Screen Shot 2021-01-26 at 11 37 10 PM" src="https://user-images.githubusercontent.com/49566929/105943497-6c33de00-602f-11eb-9d60-2e41a5af704b.png">

red squiggly on the variable

and there's no strict in my tsconfig:
```
{
    "compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es6",
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "dist"
    },
    "lib": ["es2015"]
  } 
```

**Comment by ianstormtaylor** [comment]
@theweiweiway if you enable `strict: true` does it go away? I don't believe this feature can work properly without strict mode in TypeScript.

**Comment by theweiweiway** [comment]
@ianstormtaylor  unfortunately no :(

**Comment by theweiweiway** [comment]
@ianstormtaylor  sorry, it does work! I just needed to restart my VSCode.

Thanks for the help!
