### ISSUE TITLE
recursive schema?

### ISSUE THREAD

**Issue by szhangpitt** [ianstormtaylor/superstruct#55]
Hi, I'm wondering if superstruct can support recursive schema? For example

```js

const BinaryTree = struct({
  value: 'any',
  left: struct.optional(BinaryTree),
  right: struct.optional(BinaryTree),
});

```

Intuitively I feel this should be supported already, but I don't know of a way to implement, can you advise? Thanks!

**Comment by ianstormtaylor** [comment]
Hey @szhangpitt good question! This isn't supported right now, since the `BinaryTree` will be undefined for `struct.optional(BinaryTree)` there. But I think we could allow for lazy evaluation of schemas, by wrapping them in a function. So your example would end up like:

```js
const BinaryTree = struct({
  value: 'any',
  left: struct.lazy(() => struct.optional(BinaryTree)),
  right: struct.lazy(() => struct.optional(BinaryTree)),
})
```

**Comment by nwaughachukwuma** [comment]
@ianstormtaylor, please what's meant by "pass in the type manually"

```ts
const Node = object({
  id: number(),
  children: lazy(() => array(Node)),
})
```

> 🤖 Note that TypeScript can't automatically infer the type from this kind of recursive structure, so you'll need to pass in the type manually

**Comment by nwaughachukwuma** [comment]
Ok, I solved this by doing:

```ts
type Node = {
 id: number
 children: Node
}

const Node: Describe<Node> = object({
  id: number(),
  children: lazy(() => array(Node)),
})
```
