### ISSUE TITLE
Differentiating Infer<T> type for input / output Coercions

### ISSUE THREAD

**Issue by reggi** [ianstormtaylor/superstruct#550]
I am not sure if this is already possible.

```ts
const numberOrString = coerce(number(), (value: string | number): number => {
  if (typeof value === 'number') return value;
  return parseInt(value);
});
```

```ts
const example = object({
  example: numberOrString
})
```

Currently if I use `Infer<typoef example>`  this gives `{ example: number }`.

In addition to this `Infer` generic, what I want is a type that would provide `{ example: number | string }`.

Perhaps there's a way to pull the return type input `(value: string | number)`?

Or provide it as:

```ts
coerce<number, number | string>(...
```

Is this currently possible?

**Comment by reggi** [comment]
Here's another example:

I want to be able to coerce a `string | ObjectID` to a `ObjectID`

```ts
export const NormalizeObjectId = coerce(
  union([instance(ObjectID), string()]),
  (value: ObjectID | string) => {
    if (value instanceof ObjectID) return value;
    return new ObjectID(value);
  }
);

const Document = object({
  _id: NormalizeObjectId,
});

const x = create({_id: '5fbae79fd6c23e3655a15506'}, Document);

console.log(typeof x); // object

// const x: {
//   _id: string | ObjectID;
// }
```

**Comment by ianstormtaylor** [comment]
Can you explain why you want to keep the type as the union, instead of coercing and keeping the type as the target type only?

**Comment by ianstormtaylor** [comment]
Closing because it's stale.

**Comment by Mrtenz** [comment]
> Can you explain why you want to keep the type as the union, instead of coercing and keeping the type as the target type only?

@ianstormtaylor In my case I want to accept a certain value as function input, which is then coerced. The function input should accept pre-coerced values. Currently this doesn't seem possible with `Infer`, as it narrows the types to the coerced types.

For example:

```ts
// A bigint-like value, e.g. `bigint` and `number`
const bigIntLike = coerce(bigint(), number(), BigInt);

// A function which coerces the value
const getBigInt = (value: Infer<typeof bigIntLike>): bigint => {
  return create(value, bigIntLike);
};

getBigInt(1); // Argument of type 'number' is not assignable to parameter of type 'bigint'.
getBigInt(1n);
```

The problem here is that only `bigint` is inferred from the struct, rather than `bigint | number`.
