### ISSUE TITLE
Validate string() return TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by charlesYong076** [ianstormtaylor/superstruct#552]
version: 0.12.1

```ts
const schema = object({
  first: string(),
  second: string()
});

const actual = {
  first: 1,
  second: "2"
};

validate(actual, schema );
```

expect: 
AssertionError [ERR_ASSERTION]: Event does not match expected schema: Expected a value of type `string` for `first` but
received `1`

actual:
TypeError: Cannot read property 'length' of undefined

**Comment by ianstormtaylor** [comment]
Can't reproduce on my end, can you give more information?

**Comment by charlesYong076** [comment]
Oh, is my bad. Just realize i am using validate in different repo for reuse purpose. With schema and actual value is using the latest version 0.12.1, validate repo using version 0.10.21. That's the reason why error happen. I good to get this close.
