### ISSUE TITLE
Error when trying to use `pick` utility on a Struct constructed with `Describe` utility function

### ISSUE THREAD

**Issue by nwaughachukwuma** [ianstormtaylor/superstruct#554]
Hi @ianstormtaylor, I followed your suggestion here https://github.com/ianstormtaylor/superstruct/issues/526#issuecomment-733209466 and everything works Ok except when I tried to use `pick<Struct, ['field-1', 'field-2', ... , 'field-x']>` where the `Struct` is defined using the `Describe` type utility function that helps to ensure that structs match types. For example, the following:

```ts
type User = {
  id: number
  name: string
  age: number
  address: string
}

const User: Describe<User> = object({
  id: number(),
  name: string(),
  age: number(),
  address: string()
})

const basicDetails = pick<User, ['name', 'age']>
```
will throw the error `Argument of type 'Describe<User>' is not assignable to parameter of type 'Struct<{ [x: string]: any; }, Record<string, Struct<any, any>>>'`. But if I remove `: Describe<User>` then it works Ok as expected.

**Comment by ianstormtaylor** [comment]
Hey @nwaughachukwuma can you copy the full TypeScript error? With all the nested info. Thanks!

**Comment by nwaughachukwuma** [comment]
Yes @ianstormtaylor, I only added the linter error. Let me add all I got on the terminal

> TS2345: Argument of type 'Describe<Product>' is not assignable to parameter of type 'Struct<{ [x: string]: any; }, Record<string, Struct<any, any>>>'.

> TS2322: Type '{ userId: string; pid?: any;  }' is not assignable to type 'Product'. Property 'pid' is optional in type '{ userId: string; pid?: any; }' but required in type 'Product'.

Plus let me mention that `pid` was defined as `null | string` which is a `nullable(string())` but somehow got converted to `optional(any())`.

**Comment by ianstormtaylor** [comment]
@nwaughachukwuma can you include a full sample of code and the error you get at the same time? I don't see `pid` at all in the code snippet you provided.

**Comment by nwaughachukwuma** [comment]
Ok cool. One was just an example of the shape I had used in 2. Please find a minimal example and error below to better illustrate my point:

```ts
import {string, number, Describe, object, nullable} from 'superstruct'

type Order = {
  id: string 
  pid: string | null
  userId: string
  quantity: number
}

const Product: Describe<Order> = object({
  id: string(),
  pid: nullable(string()),
  userId: string(),
  quantity: number()
})

const basicDetails = pick<Order, ['pid', 'userId']>
```

> TS2345: Argument of type 'Describe<Order>' is not assignable to parameter of type 'Struct<{ [x: string]: any; }, Record<string, Struct<any, any>>>'.

> TS2322: Type '{ userId: string; pid?: any;  }' is not assignable to type 'Order'. Property 'pid' is optional in type '{ userId: string; pid?: any; }' but required in type 'Order'.

Please let me know if this is or isn't clear enough. Thanks

**Comment by ianstormtaylor** [comment]
@nwaughachukwuma I don't appear to get the error. Is it supposed to appear on the `const Product` line? Are you using `strict` in TypeScript? And the latest TypeScript version?

Also I'm not sure what the `pick<Order ...` line is—it seems like a mixture of type-related and value-related code, but I'm not sure it's valid syntax for either.

**Comment by nwaughachukwuma** [comment]
> @nwaughachukwuma I don't appear to get the error. Is it supposed to appear on the `const Product` line? Are you using `strict` in TypeScript? And the latest TypeScript version?
> 
> Also I'm not sure what the `pick<Order ...` line is—it seems like a mixture of type-related and value-related code, but I'm not sure it's valid syntax for either.

Please look at the snippet again, I just made a correction. The long and short of this is that I'm not able to use the pick helper as shown in the documentation.

**Comment by ianstormtaylor** [comment]
@nwaughachukwuma I don't think you're using the `pick` utility correctly, at least based on that snippet. The `<...>` brackets are for typings, not for runtime values. You likely want:

```ts
import {string, number, Describe, object, nullable, pick} from 'superstruct'

type Order = {
  id: string 
  pid: string | null
  userId: string
  quantity: number
}

const Order: Describe<Order> = object({
  id: string(),
  pid: nullable(string()),
  userId: string(),
  quantity: number()
})

const basicDetails = pick(Order, ['pid', 'userId'])
```

Notice the `(...)` parentheses instead. (And you need to import `pick` as well.)
