### ISSUE TITLE
cross referencing data properties

### ISSUE THREAD

**Issue by jackmellis** [ianstormtaylor/superstruct#57]
Is there any way to validate a property by cross-referencing other data values? i.e.
```js
const schema = struct({
  foo: 'string',
  bah: (value, data) => !!(data.foo || value),
});
```

**Comment by ianstormtaylor** [comment]
Hey @jackmellis, there isn't currently, but I'd be open to that for object structs. This would match the current defaulting logic that allows cross-referencing. I'd love a PR!

**Comment by kenleytomlin** [comment]
@ianstormtaylor I'd like to see this functionality and I am happy to contribute. Would you be able to point me in the right direction?

**Comment by doodlewind** [comment]
Guess we can close this one?
