### ISSUE TITLE
Object is not fully validated before running refinements

### ISSUE THREAD

**Issue by jamiesyme** [ianstormtaylor/superstruct#596]
I was surprised by the behvaior of `refine()`. The [docs](https://docs.superstructjs.org/guides/04-refining-validation) make it sound like the struct is validated before the refinement is ever called, but it seems like the struct is only partially validated before running.

Below is an example of the weird behavior.

- Test case 1 doesn't run the refinement because `0` isn't an object. Awesome.
- Test case 2 does run the refinement because it's an object, but it doesn't have a `foo` field, so I don't think it should.
- Test case 3 does run the refinement (as expected).

```js
const { is, object, refine, string } = require("superstruct");

const MyObject = refine(
    object({
        foo: string(),
    }),
    'MyObject',
    (obj) => {
        console.log('refining');
        return true;
    },
);

console.log('1:', is(0, MyObject)); // Does not output "refining"
console.log('2:', is({}, MyObject)); // Does output "refining"
console.log('3:', is({ foo: '' }, MyObject)); // Does output "refining"
```

Tested on RunKit: https://runkit.com/embed/ilwsg9to0jxw

**Comment by ianstormtaylor** [comment]
Thanks for catching this @jamiesyme, I've fixed and added a test to ensure that nested validation always runs first!
