### ISSUE TITLE
Custom Types example is not working — context.fail is not a function

### ISSUE THREAD

**Issue by isnifer** [ianstormtaylor/superstruct#598]
Hello, I tried to reproduce different example in Demo Fiddle.
Got this issue.
![image](https://user-images.githubusercontent.com/1788245/103512692-46754800-4e7a-11eb-8549-6522ae213cb3.png)

Fiddle: https://jsfiddle.net/mgfx5yzk/4/

Checked typings:
```
/**
 * A `Context` contains information about the current location of the
 * validation inside the initial input value.
 */
export declare type Context = {
    branch: Array<any>;
    path: Array<any>;
};
```

It really does not have a function called `fail`

Update:
I found a breaking change — https://github.com/ianstormtaylor/superstruct/blob/65763f8e80a2c5ce456ec187d96a7d89d794732e/Changelog.md#breaking

Ok, this issue just a reminder — update example

**Comment by ianstormtaylor** [comment]
Thanks @isnifer!
