### ISSUE TITLE
Intersection not working with refined types

### ISSUE THREAD

**Issue by rossholdway** [ianstormtaylor/superstruct#605]
When an intersection type is passed a refined type, it doesn't actually call the refined types validation.

I would expect it to re. the documentation. Is this a bug?

> intersection structs validate that a value matches all of many structs. It takes existing struct objects as arguments.

For example:

```typescript
const PositiveInteger = refine(number(), 'PositiveInteger', (value) => {
  // Never runs
  return Number.isInteger(value) && value >= 0
})

const schema = intersection<number, number>([number(), PositiveInteger]);
assert(-10, schema); // I'd expect this to throw
```

**Comment by ianstormtaylor** [comment]
Hey @rossholdway this sounds like a bug, thanks for reporting. I'll check it out!
