### ISSUE TITLE
superstruct causes Create React App test to fail

### ISSUE THREAD

**Issue by schontz** [ianstormtaylor/superstruct#612]
superstruct causes Create React App test to fail (CRA). You will get an error along these lines:

```
Unexpected error: TypeError: superstruct_1.define is not a function
```

This is because the CRA Jest config does not look for the `.cjs` file extension. When I rename `index.cjs` to `index.js` and update `main` in `package.json` everything works as expected.

Suggestion: rename `index.cjs` to `index.js` in the build output.

**Comment by ianstormtaylor** [comment]
This sounds like a bug in one of those tools instead?

**Comment by schontz** [comment]
Well you cannot change the config of create react app without ejecting, but, yes, technically it is not the fault of superstruct. This change would be to improve compatibility in the JavaScript ecosystem. `.cjs` is not a common way to name JS files at any rate.

**Comment by DZakh** [comment]
It works with the 4th version of CRA.
Or you can temporary create your own jest.config.js with
```
moduleFileExtensions: ['cjs', 'js', 'json', 'jsx', 'ts', 'tsx', 'node'],
```
and run tests via jest directly without using react-scripts.
