### ISSUE TITLE
mask() is not recursive

### ISSUE THREAD

**Issue by dko-slapdash** [ianstormtaylor/superstruct#618]
https://codesandbox.io/s/superstruct-ff5i4-forked-ye1ns?file=/src/index.js

Notice that `zzz` is silently removed (expected), but `unk` is not (surprising). 

```
import { type, mask, number } from "superstruct";

let data = {
  id: 1,
  zzz: 444,
  some: {
    a: 10,
    unk: 55
  }
};

let Type = type({
  id: number(),
  some: type({
    a: number()
  })
});

console.log(JSON.stringify(mask(data, Type)));

// {"id":1,"some":{"a":10,"unk":55}} 
```

P.S.
I don't want to wrap all the type() I have in the code with masked(), because it produces a lot of boilerplate. I assume that the decision of stripping unknown properties is to be made at the caller side (which is likely singular) and not at the definition side (which has way higher cardinality).

**Comment by dko-slapdash** [comment]
BTW I understand that mask() is defined via masked():

![image](https://user-images.githubusercontent.com/46383452/105324451-49fa1600-5b80-11eb-96cb-23a70a00bb6b.png)

It doesn't invalidate the question though.

**Comment by ianstormtaylor** [comment]
@dko-slapdash this does sound like a good improvement. 

I think it would involve not implementing `mask` with `masked` under the covers. Instead, `mask: true` would be an option pass in to `validate` and `run` (which the `mask` function would pass). And the masking logic would be handled inside the `run` function. This would allow it to be recursive.

And at that point we could likely remove the `masked` coercion entirely.

Would you be down to make this PR?

**Comment by dko-slapdash** [comment]
I understand your idea. Unlikely I can come up with an opinionated enough PR though which also cares about backward compatibility aspects of this.

Since we discuss this code, I also think that `coerce?: boolean` option in Struct.validate() is a mistake. It should always be `true`, unconditionally and everywhere. Because look at the following schema:

https://codesandbox.io/s/superstruct-ff5i4-forked-derym?file=/src/index.js

```
let data = {
  id: 1
  //some: "aaa"
};

let Type = type({
  id: number(),
  some: nonempty(defaulted(string(), "a"))
});

console.log("!", Type.is(data));
```

Notice that `data` is a perfectly valid piece of data, but `Type.is()` returns false for it, despite validate() has a chance to successfully validate it, and it was a clear intention of the schema writer.

So I think we can have just 4 methods (only 1 of which is essential, and the rest are shortcuts), all with `mask: boolean` option (*defaulted to `true` since I strongly believe it's the right-opinionated default) and with no `coerce` option.

```
validate(value: unknown, options?: { mask: boolean = true; }): [StructError, undefined] | [undefined, T]; // never throws
create(value: unknown, options?: { mask: boolean = true; }): T; // throws what validate() returned

assert(value: unknown, options?: { mask: boolean = true }): asserts value is T; // shortcut for validate()
is(value: unknown, options?: { mask: boolean = true }): value is T; // shortcut for validate()
```

**Comment by ianstormtaylor** [comment]
@dko-slapdash there's a difference between a piece of data being "coerce-able" and being "of a given type". If you use `is` for something that is coerce-able but hasn't yet coerced there's currently no way for the typings to know that, and then if you access `data.something` it will assume it's there when it's not.

**Comment by dko-slapdash** [comment]
Oh yeah, that's right! So for assert/is, coerce is definitely always = false then.

**Comment by dko-slapdash** [comment]
> I think it would involve not implementing `mask` with `masked` under the covers. Instead, `mask: true` would be an option pass in to `validate` and `run` (which the `mask` function would pass). And the masking logic would be handled inside the `run` function. This would allow it to be recursive.

Here is the PR following the above idea: https://github.com/ianstormtaylor/superstruct/pull/629/files
