### ISSUE TITLE
let type() still keep unknown props when mask() is used

### ISSUE THREAD

**Issue by dko-slapdash** [ianstormtaylor/superstruct#619]
Hi.

Would be cool if type() allowed unknown props even if mask() is used for validation. Then, people would use object() almost everywhere, but in some rare cases they would be able to fallback to type() - and still be happy with mask().

I noticed that type() allows unknown props when used in create(), but it still strips them when used in mask(). And there is no way to tell mask() to "strip all unknown props, but for SOME EXPLICIT places - allow them".

I.e. the current logic is binary: either "throw on unknown props" (object() + create()) or "strip all unknown props (object() + mask() or type() + mask()). And there is nothing in between.

When mask() is used, object() behaves exactly the same way as type(), they're no different. I.e. in the code which uses mask() intensively (and I suspect that it is the absolute most of the code, because otherwise there would be problems with client-server backward compatibility, see below), there is no real reason in having two things - object() and type() - only one thing would be enough. Making type() preserve unknown props even when using with mask() would give its existence in a "mask()-preferred environment" a reason.

P.S.
Why I think mask() is usable in like 99% and create in like 1%: imagine we have an old client which uses `object({ a: string() })` to validate the data came from the server, and the server has just become newer: its own structure is `object({ a: string(), b: string() })`. This is a very common situation. And in this situation, create() is unusable, whilst mask() is usable.

P.P.S. 
Yup's author has recently rewrote yup to TS and made a few architectural mistakes (IMHO). One of the mistakes is to pass not a TS type in generic arguments, but the schema type itself, which blows up IntelliSense and also expands the size of the generated *.d.ts files like 10x. It also slows down the compiler. I don't think yup will survive in that state for long, so superstruct has a great advantage IMHO.

**Comment by ianstormtaylor** [comment]
Hey @dko-slapdash I think I agree with you, but can you post some example code showing a use case?

**Comment by dko-slapdash** [comment]
Well, any random struct in an environment which uses mask() - and I think that mask() is usable in 99% of cases, whilst create() is in like 1%.

```ts
const struct = object({
  title: string(),
  assignee: string(),
  customFields: array(
    type({
      some: string(),
      // and other
    })
  )
}),
```

**Comment by dko-slapdash** [comment]
(Pressed Cmd+Enter too early.) So by this structure I want to express the notion of "having arbitrary fields", but still, be able to use mask() in the code - because I want the top-level object() remove unknown keys silently.

**Comment by ianstormtaylor** [comment]
Okay yeah, I'm down for this. Can you submit a PR?
