### ISSUE TITLE
optional() deserves to be a Struct method, because it influences the TS type unlike other functions

### ISSUE THREAD

**Issue by dko-slapdash** [ianstormtaylor/superstruct#620]
Hi.

First, it's great that the opinionated default for types like string() or object() are chosen "required" and not "optional" as in e.g. yup - it produces way way less boilerplate, and it's consistent to TS types syntax.

Sometimes optional fields are used though, less frequent than required IMHO, but still. And in this case, wrapping it like `optional(string())` looks a little bit off. Also, optional() is "special": it returns a different Struct type rather than its input (as opposed to other helper functions like trimmed() or masked()), and it also affects TS type for the field (which is binary: either "optional" or "required"). I.e. it's seems like it's the only thing which is special, so I thought maybe it deserves to be presented as a Struct method; then, the syntax would be more fluent: `string().optional()` and not `optional(string())`.

![image](https://user-images.githubusercontent.com/46383452/105335112-80d62900-5b8c-11eb-887b-478e1bbc39e5.png)

**Comment by dko-slapdash** [comment]
P.S.
Actually, there is also nullable() which influences the type too. So there are 2 of them - still pretty manageable.

**Comment by ianstormtaylor** [comment]
Hey @dko-slapdash, I kind of see what you mean. But I'd prefer to not have any fluent APIs mixed in with all of the rest of the functional APIs, as discussed in #621. So I think keeping `optional/nullable` as is is best for now. The implied contract for all helpers is just that they return a new struct, not that the type signature necessarily stays the same.
