### ISSUE TITLE
make date() accept a string input?

### ISSUE THREAD

**Issue by dko-slapdash** [ianstormtaylor/superstruct#622]
JSON.stringify() successfully serializes a Date object to string, but JSON.parse() obviously doesn't do it - it just returns a string. And since JSON is often time used as a transport protocol before feeding the object to superstruct, I think the default date() deserves to have the string->Date conversion logic built in (for symmetry reasons from the above).

Currently, I have to build a custom type:

```
export function jsonDate() {
  return coerce(date(), string(), (value) => new Date(value));
}
```

But I think it won't make it worse in any of the existing people's code if it was done inside date() automatically. Actually, other validation libraries (e.g. Yup) just do it silently for their data() types, so I haven't even thought about this problem until started the migration.

**Comment by ianstormtaylor** [comment]
Hey @dko-slapdash I think that's a super valid use case. 

But I don't want the default `date` struct (or any of the core low-level structs) to add coercion out of box, because it increases the level of complexity. I think it should be something that people opt-in to.

**Comment by hemedani** [comment]
It's very important to me how can I coerce it

**Comment by hemedani** [comment]
it's work I'm sorry
