### ISSUE TITLE
Infer doesn't work for enums if the enum is in an object

### ISSUE THREAD

**Issue by theweiweiway** [ianstormtaylor/superstruct#631]
Hi!

I can get Infer to work great if I define it like so:

```
const Hi =enums(["a", "b"])

type Hi = Infer<typeof Hi>;

export const aee = () => {
  const a: Hi = "a"
};
```

<img width="296" alt="Screen Shot 2021-01-27 at 12 01 38 AM" src="https://user-images.githubusercontent.com/49566929/105945204-d601b700-6032-11eb-9e05-34554242ae0b.png">

but if the enum is defined in an object like so:
```
  const Hillo = object({
    ab: enums(["a", "b"]),
  });

  type Hillo = Infer<typeof Hillo>;

  export const ae = () => {
    const a: Hillo = {
      ab: "basdf",
    };
  };
```

Then the enum types won't work properly:

<img width="294" alt="Screen Shot 2021-01-27 at 12 01 11 AM" src="https://user-images.githubusercontent.com/49566929/105945179-c5514100-6032-11eb-8123-a38f04c7d350.png">

**Comment by xiaoyu-tamu** [comment]
you need `[a,b] as const`

**Comment by theweiweiway** [comment]
ah, thank you!
