### ISSUE TITLE
Error nesting structs

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/superstruct#68]
When trying to nest `TreeNode` structs like below I came up with error:

``` js
const Node = struct({
  id: 'number',
  children: [Node]
})
```

[JSFiddle](https://jsfiddle.net/z757neg4/2/)

Maybe I'm missing something, so how can we support such kind of validation? I can such feature pretty handy in slate's schema, is slate going to has this library as dependency?

**Comment by doodlewind** [comment]
Neither does this snippet work:

``` js
let Node
Node = struct({
  id: 'number',
  children: [Node]
})
```

I got following error:

```
superstruct.js:275 Uncaught ReferenceError: process is not defined
    at any (VM82 superstruct.js:275)
    at list (VM82 superstruct.js:550)
    at any (VM82 superstruct.js:234)
    at object (VM82 superstruct.js:633)
    at Object.any (VM82 superstruct.js:244)
    at struct (VM82 superstruct.js:1063)
    at window.onload ((index):66)
```

Related code:

```
  if (process.env.NODE_ENV !== 'production') {
    throw new Error(`A schema definition must be an object, array, string or function, but you passed: ${schema}`);
  } else {
    throw new Error(`Invalid schema: ${schema}`);
  }
```

**Comment by kenleytomlin** [comment]
Hi @doodlewind I think the lazy struct functionality is what you are looking for.

https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#lazy

This looks suitable for your use case.

**Comment by doodlewind** [comment]
@kenleytomlin thanks! That's the missing one I'm looking for.
