### ISSUE TITLE
optional enums are not assignable using Describe<Type>

### ISSUE THREAD

**Issue by bagbag** [ianstormtaylor/superstruct#693]
I need to validate optional properties which has to be one of many values. The schema definition itself should be correct, as `Infer<>`ring from it (without `Describe<TestType>`) yields the same type as `TestType`.

Am I missing something or is this a bug?

```ts
type TestType = {
  foo?: 'bar' | 'baz'
};

const testTypeSchema: Describe<TestType> = object({
  foo: optional(enums(['bar', 'baz'] as const))
});
```

```
Type 'Struct<{ foo?: "bar" | "baz" | undefined; }, { foo: Struct<"bar" | "baz" | undefined, { bar: "bar"; baz: "baz"; }>; }>' is not assignable to type 'Describe<TestType>'.
  Types of property 'schema' are incompatible.
    Type '{ foo: Struct<"bar" | "baz" | undefined, { bar: "bar"; baz: "baz"; }>; }' is not assignable to type '{ foo?: Describe<"bar" | "baz" | undefined> | undefined; }'.ts(2322)
```

**Comment by ianstormtaylor** [comment]
Looks like it has to do with the `?` operator, which is a little finicky. Do you have `"strict": true` mode enabled in your TypeScript config?

**Comment by bagbag** [comment]
Yes, my tsconfig is as strict as it can be.

**Comment by ianstormtaylor** [comment]
Hmm, not sure in that case. If you dig in and have questions as you go I'd be happy to advise however I can though! My guess is it's a bug (or potentially a TS limitation) in how the undefined logic is typed. If you do figure it out a PR would be awesome.
