### ISSUE TITLE
Recommended way to "cast" between similar types

### ISSUE THREAD

**Issue by nhagen** [ianstormtaylor/superstruct#710]
We have complex data structures stored in a database that can be reduced to much simpler data structures by convention. An extremely contrived example:
```
{
  type: 'MyVerySpecificTypeOfThing',
  and: { or: { and: { or: ['a', 'b'] } } }
}
```
can be reduced by convention to
```
{
  type: 'GeneralTypeOfThingForThisContext',
  allowedItems: ['a', 'b']
}
```
On the frontend, we like to work with `GeneralTypeOfThingForThisContext` objects, and then transform them into remote `MyVerySpecificTypeOfThing` objects.

They contain the same data, but are just different formats. I can make structs like this:

```
let RemoteObject = object({
  type: literal('MyVerySpecificTypeOfThing'),
  and: object({ or: object({ and: object({ or: array(string()) }) }) })
})

let LocalObject = object({
  type: literal('GeneralTypeOfThingForThisContext'),
  allowedItems: array(string())
```

Is there a way to use `superstruct` for casting between these structs? Or is a function like `transformLocalToRemote(localObject)` the cleanest way to do this?

**Comment by ianstormtaylor** [comment]
@nhagen it sounds like having your own `transform*` functions would be the way to go there.
