### ISSUE TITLE
Serverless and cold start environments.

### ISSUE THREAD

**Issue by rubybb** [ianstormtaylor/superstruct#711]
I'd assume since this package somehow gains a performance boost slightly from compiling the validation logic once, then using it repeatedly, however in cold start environments this is rather redundant as it'll have no gain. Is there a way we could compile at build time, or perhaps something similar? If not I'd love for this to be a feature.

**Comment by ianstormtaylor** [comment]
Hey @rubybb I'm honestly not sure, but this only matters when compared to libraries that would for example store complex validation as strings. I haven't done any perf tests on this, so I wouldn't want to give any assurances. My guess is for most use cases it won't matter much, so you're probably fine.
