### ISSUE TITLE
Cannot find module 'superstruct/lib/coercions'

### ISSUE THREAD

**Issue by Poliziano** [ianstormtaylor/superstruct#712]
I am trying to use the `masked` function to create a masked version of an object. My project has compiled before using the `masked` function, but since adding it I am unable to compile. I can clearly see that the file it is after is there, so I'm quite confused what is wrong.

```typescript
import { object } from 'superstruct';
import { masked } from 'superstruct/lib/coercions';

 masked(object({}))
```

I get the feeling that the `masked` function should be imported from the first import, but it is not available. I am using version `0.14.2`.

**Comment by ianstormtaylor** [comment]
Please check the change log.

**Comment by Poliziano** [comment]
Please update the documentation for this page: https://docs.superstructjs.org/api-reference/coercions#masked

**Comment by ianstormtaylor** [comment]
Hmm looks like GitBook isn't using the latest `main` branch, I'll check it out.
