### ISSUE TITLE
Validate full structure

### ISSUE THREAD

**Issue by andre2** [ianstormtaylor/superstruct#76]
Hi,

I need help :(
I any option to validate full structute and return all errors?

My current solution show first found error in structure

**Comment by doodlewind** [comment]
Not sure about what "full" means. Is your data recursive?
If possible, could you provide JSFiddle as demo?

**Comment by ianstormtaylor** [comment]
Hey @andre2 if you're referring to getting multiple errors, there is an `error.errors` property containing all of the errors for the current level of validation. Superstruct throws a single error for convenience, since most use cases don't need multiple, but the others are provided there.
