### ISSUE TITLE
Add showcase field in README

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/superstruct#77]
Hi Ian, thanks for your work, Superstruct works great!

For the past days I was working with a library called [Bumpover](https://github.com/doodlewind/bumpover) that deals data migration, whose data validation API relies on Superstruct. This library is usable for now, so how about adding its link to a "Showcase" or "Related" field in README? The more scenarios using Superstuct, the more popularized it is.

**Comment by ianstormtaylor** [comment]
Hey @doodlewind, sounds good to me! I'd be open to a PR that adds a "Showcase" section to a `./docs/resources.md` file, like we [do for Slate](https://github.com/ianstormtaylor/slate/blob/master/docs/general/resources.md), if you were down to PR it. Thanks!
