### ISSUE TITLE
Providing Context to Type Functions

### ISSUE THREAD

**Issue by simplygreatwork** [ianstormtaylor/superstruct#78]
Thank you for publishing superstruct - amazing clarity.

I am defining schemas in YAML and using superstruct to validate. If I want to do bounds checking for integers, for example, I have to resort to using struct.function(). I can't use types for this scenario because only the value is passed in (edit) - and not the key of the validated data property. If the key were passed to the type validation function, I could bind to that function to look up the additional schema parameters I need. 

Please consider if it would be a good idea or a bad idea to pass along additional parameters to the type validation function.

**Comment by ianstormtaylor** [comment]
Hey @simplygreatwork, good question!

Do you have an example of the struct your are validating with? And what the data looks like?

**Comment by simplygreatwork** [comment]
In the superstruct docs, the age type example had bounds embedded inside the type function. I would like to be able to validate bounds from a schema.

YAML schema
```yaml
---
  type: Person
  properties:
    age:
      type: 'number?'
      range: [18, 120]
```
To do this currently, I am using struct.intersection to compose the number type with struct.function to do the bounds checking. I think this is the correct approach for now even if struct.function is an escape hatch.
```javascript
var config = {};
var properties = schema.properties;
for (var key in properties) {
    var object = properties[key];
    config[key] = object.type;
    if (object.range) {
        config[key] = struct.intersection([config[key], struct.function(function(value) {
            return (value >= object.range[0]) && (value <= object.range[1]);
        })]);
    }
}
var Person = struct(struct_config);
```
But an alternative could be for type functions to be passed a second argument, the key of the property being validated.
```javascript
types : {
    age : function(value, key) {
        if (this.properties[key].range) {
            var range = this.properties[key].range;
            return (value >= range[0]) && (value <= range[1]);
        }
    }.bind(schema)      // binding a schema definition to become "this" above
}
```
Let me know if you want to express this in more detail. I'm mainly observing that values are passed into type functions - without any other context.

**Comment by ianstormtaylor** [comment]
@simplygreatwork I'm not sure what the `this.properties` piece is there? Or how the `range` itself is being passed in? Could you try writing up the struct definition with the current API but with your tweak applied? I think bridging the gap from YAML to JS is confusing me.

What I'd recommend though is actually treating "age" as a type itself, where it has a fixed range of `18–120` or whatever makes sense for your application's problem space.

**Comment by simplygreatwork** [comment]
You don't need to change anything in superstruct. It is super rad as it is. I'm OK with using struct.function. Above, "this.properties" is actually "schema.properties" because I used the bind keyword to bind "schema" to "this". "schema.properties" is just an associative array of objects defining properties of my schema.

In superstruct, I do love that I can create new high-level types. That works great when superstruct and JavaScript are the single source of truth for my system. But if a YAML document is my single source of truth across multiple programming languages, then implementing number bounds checking is more low level or portable than validating an age type in multiple programming languages.

I was mainly proposing that you consider passing a second argument to each type function: the key of the property being validated.
