### ISSUE TITLE
consider adding value coercion

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/superstruct#8]
This can sometimes be useful, for example when you require numbers, but a string of a number was passed in. If there was a coercion step before validation it would account for that.

**Comment by mycaule** [comment]
You can already do this.

```
imageHeight: 'string | number',
```

**Comment by mycaule** [comment]
Here is a sample piece of code for an implementation of the [DuckDuckGo Instant Answer API](https://duckduckgo.com/api).

https://github.com/mycaule/knowledge-graph-js/blob/master/services/duckduckgo.js

```
  ImageIsLogo: 'empty | number',
  ImageHeight: 'empty | number',
  ImageWidth: 'empty | number',
```

 The response can be pretty complex. I retro-engineered their contract with your library.

**Comment by huanz** [comment]
I'm also looking forward to this and for `struct.enum` ，eg：

```javascript
{
    status: shape.enum([0, 1, 2])
}
```

the params passed from a request may be a string，now i must do like this

```javascript
{
    status: shape.enum([0, 1, 2, '0', '1', '2'])
}
```
I hope there's a better way to deal with it

**Comment by ianstormtaylor** [comment]
The main place this has come up for me has been parsing query parameters. But I'm not actually convinced that that is a reason to add this Superstruct, because I think the query parameters case makes more sense as a request-layer middleware. (For example, I've added a Koa middleware to my stack to handle this for me instead.)

If others can provide other good use case examples that would be helpful, otherwise I'm tempted to avoid doing this for complexity's sake.

**Comment by huanz** [comment]
@ianstormtaylor I don't think it's appropriate to do it in the middleware. Because we don't know what parameters are compatible, we can't convert all the string types into numbers in the middleware? Or do you have any good advice?

**Comment by huanz** [comment]
@ianstormtaylor Now I use it to check my request parameters, and I have found another problem.

```javascript
let params = struct(schema, defaults)(this.request.body);
```

If the parameter is not defined in schema , it will be checked into undefined.

But what I want is that the parameters not defined in schema do not make any verification and return directly to me. 

I hope you can think about it.

**Comment by ianstormtaylor** [comment]
@huanz for that I think you might want `struct.partial`. Although that will ignore the non-defined values in the returned object.

**Comment by lxcid** [comment]
> If others can provide other good use case examples that would be helpful, otherwise I'm tempted to avoid doing this for complexity's sake.

For my use case, I'm returning value from Redis, which almost all values are represented as string.
I had a step where I turn dot separated keys in a hash into a nested structure (using lodash's set), which is validate with superstruct.

A lot of the rules are available in the schema, but i can't use that information to coerce the values, so I end up having to process the value separately (which kinda default the purpose of superstruct (checking for null, if not turn it into integer). Or if I want superstruct to pass, I would have to be lenient with my schema. Both not that ideal.

**Comment by ianstormtaylor** [comment]
After thinking about this more, I think it doesn't make sense to add it.

The trouble with coercing values is that you end up in a catch-22. Say you were building an API where users could pass in an `?expand=` query parameter. Internally, you don't deal with strings, but the parsed array of strings:

```js
const Expand = struct.list([struct.enum(['user', 'team'])])

Expand(['user']) // OK
Expand(['user', 'teams']) // OK
```

This is problematic because you get the concatenated string when accessing the query parameters:

```js
Expand('user,teams') // ERROR!
```

You might want to right a coercion step, somehow, like:

```js
const Expand(['string'], [], value => typeof value === 'string' ? value.split(',') : value)

Expand(['user', 'teams']) // OK
Expand('user,teams') // OK
```

But by doing this, you've had to re-write your own type-checking logic for each of the coercion steps. For strings it's okay, but for nested objects it gets really repetitive. And you've loosened the API your business logic acts on. The errors that will be thrown for this code path are less knowable than before. What happens if someone passes a string but it's invalid like `'20le2&&'`. Your business logic shouldn't know about querystring parsing, but now to provide a useful error it has to know that sometimes `Expand` is expressed as strings. And this is a simple case.

Instead, it's likely better to model the query parameters as a separate struct, wrapped in its own coercion logic...

```js
const ExpandParam = struct.regexp(/\w+(,\w+)+/)

const parseExpandParam = param => {
  const string = ExpandParam(param)
  return string.split(',')
}
```

That way you can separate the behaviors. You can parse the query logic at the routing layer, and your business logic only ever sees proper arrays.

Of course, you can always build the all-in-one option yourself in a single function by using two structs and then keeping it one place. If you really want to. But this way Superstruct stays much simpler, while still making that option possible.

So I'm going to close this for now. But if someone has good counter arguments though I'm open to revisiting!
