### ISSUE TITLE
Feature Request: chainable refinement

### ISSUE THREAD

**Issue by Louis-Tian** [ianstormtaylor/superstruct#813]
Hi @ianstormtaylor, 

thanks for the library, really enjoy using it.

Is there any plan for supporting a chainable API for refinements? Something similar to how `Joi`'s API looks like.
It's obviously a personal preference, but I find the chainable refinements is a lot more readable than nested function calls.

For example, 
In superstruct, we would do something like `defaulted(trimmed(string()), "foo")`. 
A chainable API might look like `string().trimmed().defaulted("foo")`

**Comment by VeryCrazyDog** [comment]
@Louis-Tian Did you check #621?

**Comment by Louis-Tian** [comment]
> @Louis-Tian Did you check #621?
Aha, that does answers my question. Thanks
