### ISSUE TITLE
Comparing Fields

### ISSUE THREAD

**Issue by 67726e** [ianstormtaylor/superstruct#820]
I'm working on a fairly straightforward problem, comparing a password to a confirmation field. I have found a [prior issue](https://github.com/ianstormtaylor/superstruct/issues/123), however the answers provided appear out-of-date and in reference to long-gone APIs. I was able to effect a solution, however I'm not quite sure if this is the right approach and if there are errors lurking:

Note: I have based the parameter names on information in the aforementioned answers, but I cannot find a definitive API definition for the `define` method in the documentation so I'm not sure if those are correct.

```
export const match = (field) => define('match', (value, { branch, path }) => {
        if (branch[0][field] === value) {
                return true;
        } else {
                return false;
        }
});
```

**Comment by 67726e** [comment]
Looks like I have the correct definition / destructuring of the `Context` into `{ branch, path }`

https://github.com/ianstormtaylor/superstruct/blob/main/src/struct.ts#L241
https://github.com/ianstormtaylor/superstruct/blob/main/src/struct.ts#L204

**Comment by RWOverdijk** [comment]
```js
if (branch[0][field] === value) {
  return true;
} else {
  return false;
}
```

I don't know the answer but I can point out injustices when I see them. Don't do this ☝️ Instead just:

`return branch[0][field] === value;`

**Comment by 67726e** [comment]
@RWOverdijk - I've written the `true` / `false` return as a stub for eventually writing proper Superstruct error messages, but thank you for chaffing this conversation.

**Comment by ianstormtaylor** [comment]
Looks alright to me if it works.
