### ISSUE TITLE
Document mask()

### ISSUE THREAD

**Issue by dimaqq** [ianstormtaylor/superstruct#848]
https://docs.superstructjs.org/?q=mask has a couple of mentions of the `mask()` qualifier, and they are well hidden.

IMO, masking is quite important, somewhere on par with Validating Data/Composed Values.

Now that it works (correctly?) #629 it would be awesome to advertise it.

**Comment by dimikot** [comment]
This can be closed now, since https://github.com/ianstormtaylor/superstruct/pull/1070 is merged - @ianstormtaylor

**Comment by dimaqq** [comment]
Thank you 💟
