### ISSUE TITLE
Support defaulted() in the assert

### ISSUE THREAD

**Issue by arash-bizcover** [ianstormtaylor/superstruct#871]
Currently "You must use create(value, Struct) on the value to have the coercion take effect! Using simply assert() or is() will not use coercion."

It would be only useful if we had this feature (defaulted()) inside the assert so when we assert, it added the missing field automatically.

example wishing it was working:

```javascript
let data ={ name: "b" }

assert(data, type({
    name: string(),
    group: defaulted(string(), "Bs"),
}))
```

**Comment by ianstormtaylor** [comment]
I believe that's how `create` works already. It can't happen in `assert` because it would need to return the object or mutate it.
