### ISSUE TITLE
Support for unknown properties

### ISSUE THREAD

**Issue by dimitarkolev** [ianstormtaylor/superstruct#88]
I cant find it in the documentation. Is it possible to have struct validate an object that has properties not listed in the schema?

**Comment by ianstormtaylor** [comment]
@dimitarkolev yup! I’m on my phone right now, but it should be in the docs under `partial` I think.

**Comment by dimitarkolev** [comment]
I cant find anything related to partial in the documentation, but i found in the source :) Many 10x

**Comment by fabioricali** [comment]
See this https://github.com/fabioricali/valify/blob/master/README.md#detect-unknown-fields

**Comment by ianstormtaylor** [comment]
Documented now!
