### ISSUE TITLE
How can I get the original schema?

### ISSUE THREAD

**Issue by timwis** [ianstormtaylor/superstruct#91]
Hello, I've just built [koa-superstruct](https://github.com/timwis/koa-superstruct) to use superstruct as a validation library with koa, but I've run into an issue when working with the results of `struct.optional(schema)`. As you can see in the [few lines of code](https://github.com/timwis/koa-superstruct/blob/master/index.js), in order to determine which properties of the koa `ctx` object to validate, `koa-superstruct` looks at the schema's top level properties it was passed, ie. `body`, `query`, `params`. This works fine with something like `struct({ body: {...} })`, but if you use `struct.optional({ body: {...} })`, `koa-superstruct` can't seem to access the schema object (`{ body: {...} }`), and instead it's a `union` object. So it doesn't know to pass koa's `ctx.request.body`.

Is there a way to get the original schema object? Or is there, perhaps, a better way to approach this?

**Comment by ianstormtaylor** [comment]
Hey @timwis sorry for the delay here. As currently architected, you're right it makes that kind of introspection hard. I'd be open to ideas for how to make it easier. I think it might be complex to do in a way that preserves the logic going down? Not sure!
