### ISSUE TITLE
How to make all properties optional?

### ISSUE THREAD

**Issue by timwis** [ianstormtaylor/superstruct#92]
I'm trying to validate for `POST` and `PATCH`. On `POST`, I'm creating a new resource, which requires most fields and only has a couple optional. For `PATCH`, all fields are essentially optional.

Is there a way to convert my schema to "all fields are optional," or do I need to have two schemas? I was hoping that's what `struct.optional()` did, but that seems to make the _entire object_ optional.

**Comment by szhangpitt** [comment]
^^^ this is probably the simplest way to go. I have something similar in my code.

**Comment by roccomuso** [comment]
thanks

**Comment by ianstormtaylor** [comment]
Interesting, there might be a way this could be made easier by allow `struct.partial` to take in an existing object struct and convert it? I'd be open to ideas here.
