### ISSUE TITLE
Error when using superstruct in an older browser

### ISSUE THREAD

**Issue by chisrcastro** [ianstormtaylor/superstruct#93]
Hello! I tried importing superstruct in my frontend project and it works fine when I test it on my latest Chrome browser. However, it raises an error when I test it on an older browser. The issue can be reproduced using the live js fiddle demo:

The live demo (https://jsfiddle.net/yjugaeg8/2/) works fine when I run it on the latest Chrome browser.

But when I run it on an older browser, Safari 9.1.2, it raises an error. I converted all modern js code to classic js in the live demo (https://jsfiddle.net/6skrmosh/8/) but it seems that the superstruct.js file included in the demo has modern js syntax that causes the error:

<img width="1440" alt="screen shot 2018-02-22 at 11 28 03 am" src="https://user-images.githubusercontent.com/869372/36518922-845568f8-17c3-11e8-9bd0-696dc94ed347.png">

Line 16 points to:
```
    const { data, value, type, path, reason, errors = [] } = attrs;
```

**Comment by doodlewind** [comment]
Are you using the UMD build directly? Simply using module bundlers to transpile JS may handle this.

**Comment by chisrcastro** [comment]
@doodlewind Thank you for responding! I installed superstruct via yarn and imported it to my code using `import { struct } from 'superstruct';`. The bundlers handle my other js code well, but for some reason, the superstruct code has remaining modern js code in the bundled js output.

**Comment by doodlewind** [comment]
Well I guess this is to do with #83 since superstruct release itself in ES6. Bundling superstruct into ES5 can solve this, as a workaround for now, you can config babel-loader or uglify to transform superstruct.

**Comment by chisrcastro** [comment]
@doodlewind I see. Thank you for the suggestion! 👍I'll close this issue now since it might be related to #83
