### ISSUE TITLE
Get type out of struct?

### ISSUE THREAD

**Issue by kentcdodds** [ianstormtaylor/superstruct#938]
Let's say I have a component that accepts a user:

```tsx
const UserStruct = object({id: string(), avatar: string()})
type User = {id: string, avatar: string}

function Avatar({user}: {user: User}) {
  // ...
}

function App() {
  // somehow we get the user from an untyped source like an HTTP request
  declare const user: unknown

  assert(user, UserStruct)

  return <Avatar user={user} />
}
```

Notice that I have to basically manually keep the `UserStruct` and the `User` in sync. Would it be possible to derive the `User` type from the `UserStruct` so that could be the source of truth? If so, I couldn't find anything about that in the docs.

**Comment by kentcdodds** [comment]
Found it! https://docs.superstructjs.org/guides/06-using-typescript#inferring-types

**Comment by the-yamiteru** [comment]
This doesn't really work since it shows that Initial type is unknown.
