### ISSUE TITLE
Expose `StructError` message formatter directly

### ISSUE THREAD

**Issue by lukeed** [ianstormtaylor/superstruct#94]
It'd be nice to have access to the formatter directly. It can be used within (and exported from) the same file to create the `message`.

Currently, if you have multiple errors and want to format them, you'd have to go thru the "work" on instantiating a new class per error, just to take the message string.

```js
let messages = err.errors.map(attr => (new StructError(attr)).message);

// vs

function toMessage(o) {
  return `Expected a value of type \`${o.type}\`${o.path.length ? ` for \`${o.path.join('.')}\`` : ''} but received \`${JSON.stringify(o.value)}\`.`;
}

let messages = err.errors.map(toMessage);
```

**Comment by ianstormtaylor** [comment]
@lukeed interesting, I'd be down for that. I think it could be nice to expose it as a static method as `StructError.format(attrs)`, if you want to PR!
