### ISSUE TITLE
Optional enum custom type

### ISSUE THREAD

**Issue by Barterr** [ianstormtaylor/superstruct#97]
I'm defining a custom type which is an enum, and with that I want one property to be optional of that custom type, however this is not being optional, it's expecting it to exist.

I modified the demo to show the problem:

https://jsfiddle.net/yjugaeg8/98/

This works and is optional:
`struct.optional(struct.enum(['USER', 'ADMIN']))`

These two don't work, the field becomes required and not optional:
`altStruct.optional('userRole')`
`'userRole?'`

userRole was defined like this:
```
const altStruct = superstruct({
  types: {
    userRole: struct.enum(['USER', 'ADMIN']),
  },
});
```

Am I doing something wrong here?

I can just use the one that works, however I'd like to have it as a custom type so I can reuse elsewhere.

**Comment by Barterr** [comment]
Solved by defining userRole like this:
`userRole: value => ['USER', 'ADMIN'].includes(value),`

However I imagined the enum would work the same way

**Comment by ianstormtaylor** [comment]
Ah yeah when defining a type it’s always by defining a function that returns `true/false` based on validity. You shouldn’t use the strict to define types. Those are only after having defined types.
