### ISSUE TITLE
Coercions nested inside object doesn't work 

### ISSUE THREAD

**Issue by PoyangLiu** [ianstormtaylor/superstruct#971]
Example
```
const CoercedDate = coerce(date(),string(), (dateString) => {
    return new Date(dateString);
});

const UserId = string();

const User = object({
    createdAt: CoercedDate,
    name: string()
});

const facilityValidator = object({
    createdAt: CoercedDate,
    user: union(UserId, User),
});

const facility = {
    createdAt: '2021-10-10T10:10:10.100Z',
    user: {
        createdAt: '2021-11-11T11:11:11.111Z', // This should be coerced, but is not
        name: 'hal',
    },
}

const [error] = validate(facility, facilityValidator, { coerce: true, mask: false });
// "At path: user -- Expected the value to satisfy a union of `string | object`, but received: [object Object]"
```

**Comment by PoyangLiu** [comment]
I dig into the code a bit, and perhaps in [line 151](https://github.com/ianstormtaylor/superstruct/blob/v0.15.3/src/utils.ts#L151) of `utils.ts`
```
129   const ctx: Context = { path, branch }
...
151   for (const failure of struct.validator(value, ctx)) {
152     valid = false
153     yield [failure, undefined]
154   }
```
The `ctx` passed intoi the `struct.validator` function  should've included `coerce` boolean but it doesn't (see line 129)?

**Comment by ianstormtaylor** [comment]
Hey, I believe this is an issue with `union` specifically. @yss14 to your question, I think it has to do with `union` not having an `entries` definition—which allows structs to loop over there children to recurse deeper into the value (objects, arrays, etc.). If a flexible `entries` method was added I think this would be solved?
