### ISSUE TITLE
Option to disable runtime assertion in production

### ISSUE THREAD

**Issue by ArturBaybulatov** [ianstormtaylor/superstruct#975]
Hey, thanks for an amazing lib!

Is there a way to disable runtime type validation in a production environment so that performance isn't affected?

**Comment by paambaati** [comment]
This is an interesting use-case; I'm genuinely curios – what are you `superstruct` for if not for its runtime validation? Only for the type information?

**Comment by ArturBaybulatov** [comment]
No-no, I do use superstruct for runtime validation in development environment all the time. But sometimes only in production environment (controlled by the `NODE_ENV` system env. variable) I want to disable certain validations to reduce potential throws in the app, especially when I'm certain that the possibility on an invalid data is minimal.

There is a practice of disabling debug assertions in other languages, e.g. C/C++:

> When a program is deployed to production, assertions are typically turned off, to avoid any overhead or side effects they may have. In some cases assertions are completely absent from deployed code, such as in C/C++ assertions via macros. In other cases, such as Java, assertions are present in the deployed code, and can be turned on in the field for debugging.

https://en.wikipedia.org/wiki/Assertion_(software_development)#Assertions_in_production_environment

**Comment by mikestopcontinues** [comment]
Is the performance hit that bad? You can never really anticipate what craziness prod will throw at your code. I gladly take the hit, and use Sentry.io to capture those errors.

**Comment by ianstormtaylor** [comment]
@ArturBaybulatov interesting use case. It feels like you could make wrapper `assert`/`is` functions that were silent in development if you needed this logic? I'm not sure if it should be in core as a default because it feels a little dangerous to encourage.

**Comment by ArturBaybulatov** [comment]
> Is the performance hit that bad?

I haven't noticed or measured any in my projects, though I've used Superstruct for quite some time. I was more thinking about potential impact.
